In [76]:
import pandas as pd
df = pd.read_csv("DS-jobs.csv")

In [12]:
df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Sr Data Scientist,$137K-$171K (Glassdoor est.),Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna"
1,1,Data Scientist,$137K-$171K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1
2,2,Data Scientist,$137K-$171K (Glassdoor est.),Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,$137K-$171K (Glassdoor est.),JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech..."
4,4,Data Scientist,$137K-$171K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

Data Cleaning and Preprocessing
1. Detailed Parsing of Salary Information:

• Remove Currency Symbols: Remove ”$” or other currency sym-
bols from ”Salary Estimate” to simplify the salary parsing process.

• Salary Type Extraction: Create a column that identifies whether

the salary is presented as ”per year,” ”per hour,” etc., based on com-
mon indicators in ”Salary Estimate.”

2. Handle Special Characters in Text Columns:
• Text Standardization: Remove or replace special characters (e.g.,
”\n”, ”\t”, and other symbols) from columns like ”Job Description”
and ”Company Name” for consistency.

• Lowercasing: Convert all text columns (e.g., ”Job Title,” ”Com-
pany Name,” ”Industry”) to lowercase to standardize the format and

avoid case sensitivity issues during analysis.
3. Company Name Refinement:
• Remove Rating from Company Name: Clean up ”Company
Name” by removing any appended rating values (e.g., ”Company
Name\n3.8”).
• Unique Company Identifier: Generate a unique identifier for each

company based on the cleaned ”Company Name” to help with com-
parisons.

4. Standardizing Location Data:
• Expand State Abbreviations: For the ”Location” column, expand
state abbreviations (e.g., ”CA” → ”California”) to ensure uniformity.

• Location Format Consistency: Check for any inconsistent for-
mats in ”Location” and ”Headquarters” and standardize to ”City,

State” format.
• Distance Calculation: If city and state information are available,
create approximate distance calculations between ”Location” and
”Headquarters” to identify remote positions.
5. Revenue Column Parsing and Cleaning:
• Extract Revenue Range: For each value in ”Revenue,” extract
minimum and maximum revenue values to separate columns.
• Currency Standardization: Ensure all revenue values are in the

same currency (e.g., USD) and handle conversions if any foreign cur-
rencies are detected.

• Fill Missing Values in Revenue: Fill missing values in the ”Rev-
enue” column.

In [77]:

df['Salary Type'] = df['Salary Estimate'].apply(lambda x: 'per hour' if 'per hour' in x.lower() else ('per year' if 'per year' in x.lower() else ('per day' if 'per day' in x.lower() else 'per year')))
df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Salary Type
0,0,Sr Data Scientist,$137K-$171K (Glassdoor est.),Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",per year
1,1,Data Scientist,$137K-$171K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,per year
2,2,Data Scientist,$137K-$171K (Glassdoor est.),Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1,per year
3,3,Data Scientist,$137K-$171K (Glassdoor est.),JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",per year
4,4,Data Scientist,$137K-$171K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",per year

In [78]:
#1
df['Salary Estimate'] = df['Salary Estimate'].str.replace('[£$€₹]', '',regex=True)
df['Salary Estimate']=df['Salary Estimate'].str.replace("K","000")

df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Salary Type
0,0,Sr Data Scientist,137000-171000 (Glassdoor est.),Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",per year
1,1,Data Scientist,137000-171000 (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,per year
2,2,Data Scientist,137000-171000 (Glassdoor est.),Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1,per year
3,3,Data Scientist,137000-171000 (Glassdoor est.),JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",per year
4,4,Data Scientist,137000-171000 (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",per year

In [79]:


#2
import re
def remove_special_char(Text):
  cleaned_text=re.sub(r"[^a-zA-Z0-9]","",Text)
  cleaned_text=re.sub(r"\s+","",cleaned_text)
  return cleaned_text


  df["Job Description"]=df["Job Description"].apply(remove_special_char)


  df["Company Name"]=df["Company Name"].apply(remove_special_char)

In [18]:
  df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Salary Type
0,0,Sr Data Scientist,137000-171000 (Glassdoor est.),Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",per year
1,1,Data Scientist,137000-171000 (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,per year
2,2,Data Scientist,137000-171000 (Glassdoor est.),Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1,per year
3,3,Data Scientist,137000-171000 (Glassdoor est.),JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",per year
4,4,Data Scientist,137000-171000 (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",per year

In [80]:
df["Job Description"]=df["Job Description"].str.replace("\n",' ',regex=True).str.replace("\t","",regex=True).str.replace("\r","",regex=True)
df["Company Name"]=df["Company Name"].str.replace("\n",' ',regex=True).str.replace("\t","",regex=True).str.replace("\r","",regex=True)
df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Salary Type
0,0,Sr Data Scientist,137000-171000 (Glassdoor est.),Description The Senior Data Scientist is resp...,3.1,Healthfirst 3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",per year
1,1,Data Scientist,137000-171000 (Glassdoor est.),"Secure our Nation, Ignite your Future Join th...",4.2,ManTech 4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,per year
2,2,Data Scientist,137000-171000 (Glassdoor est.),Overview Analysis Group is one of the larges...,3.8,Analysis Group 3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1,per year
3,3,Data Scientist,137000-171000 (Glassdoor est.),JOB DESCRIPTION: Do you have a passion for Da...,3.5,INFICON 3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",per year
4,4,Data Scientist,137000-171000 (Glassdoor est.),Data Scientist Affinity Solutions / Marketing ...,2.9,Affinity Solutions 2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",per year

In [81]:
df=df.apply(lambda x:x.str.lower() if x.dtype=='object' else x)
df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Salary Type
0,0,sr data scientist,137000-171000 (glassdoor est.),description the senior data scientist is resp...,3.1,healthfirst 3.1,"new york, ny","new york, ny",1001 to 5000 employees,1993,nonprofit organization,insurance carriers,insurance,unknown / non-applicable,"emblemhealth, unitedhealth group, aetna",per year
1,1,data scientist,137000-171000 (glassdoor est.),"secure our nation, ignite your future join th...",4.2,mantech 4.2,"chantilly, va","herndon, va",5001 to 10000 employees,1968,company - public,research & development,business services,$1 to $2 billion (usd),-1,per year
2,2,data scientist,137000-171000 (glassdoor est.),overview analysis group is one of the larges...,3.8,analysis group 3.8,"boston, ma","boston, ma",1001 to 5000 employees,1981,private practice / firm,consulting,business services,$100 to $500 million (usd),-1,per year
3,3,data scientist,137000-171000 (glassdoor est.),job description: do you have a passion for da...,3.5,inficon 3.5,"newton, ma","bad ragaz, switzerland",501 to 1000 employees,2000,company - public,electrical & electronic manufacturing,manufacturing,$100 to $500 million (usd),"mks instruments, pfeiffer vacuum, agilent tech...",per year
4,4,data scientist,137000-171000 (glassdoor est.),data scientist affinity solutions / marketing ...,2.9,affinity solutions 2.9,"new york, ny","new york, ny",51 to 200 employees,1998,company - private,advertising & marketing,business services,unknown / non-applicable,"commerce signals, cardlytics, yodlee",per year

In [82]:
#3
df["Company Name"] = df.apply(lambda x: x["Company Name"].replace(str(x["Rating"]), "", 1) if str(x["Rating"]) in x["Company Name"] else x["Company Name"], axis=1)

In [83]:
company_ids = {}
def create_company_id(company_name):
  if company_name not in company_ids:
    company_ids[company_name]=len(company_ids)+1
  return company_ids[company_name]

In [84]:
df["Company ID"]=df["Company Name"].apply(create_company_id)
df.tail()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Salary Type,Company ID
667,667,data scientist,105000-167000 (glassdoor est.),summary we’re looking for a data scientist to...,3.6,tranzact,"fort lee, nj","fort lee, nj",1001 to 5000 employees,1989,company - private,advertising & marketing,business services,unknown / non-applicable,-1,per year,432
668,668,data scientist,105000-167000 (glassdoor est.),job description become a thought leader within...,-1.0,jkgt,"san francisco, ca",-1,-1,-1,-1,-1,-1,-1,-1,per year,433
669,669,data scientist,105000-167000 (glassdoor est.),join a thriving company that is changing the w...,-1.0,accesshope,"irwindale, ca",-1,-1,-1,-1,-1,-1,-1,-1,per year,434
670,670,data scientist,105000-167000 (glassdoor est.),100 remote opportunity as an ainlp data scient...,5.0,chateck incorporated,"san francisco, ca","santa clara, ca",1 to 50 employees,-1,company - private,advertising & marketing,business services,$1 to $5 million (usd),-1,per year,435
671,671,data scientist,105000-167000 (glassdoor est.),description the data scientist will be part o...,2.7,1-800-flowers,"new york, ny","carle place, ny",1001 to 5000 employees,1976,company - public,wholesale,business services,$1 to $2 billion (usd),-1,per year,365

In [85]:
#4
us_state_abbrev = {
    'AL': 'Alabama', 'AK': 'Alaska', 'AZ': 'Arizona', 'AR': 'Arkansas', 'CA': 'California',
    'CO': 'Colorado', 'CT': 'Connecticut', 'DE': 'Delaware', 'DC': 'District of Columbia',
    'FL': 'Florida', 'GA': 'Georgia', 'HI': 'Hawaii', 'ID': 'Idaho', 'IL': 'Illinois',
    'IN': 'Indiana', 'IA': 'Iowa', 'KS': 'Kansas', 'KY': 'Kentucky', 'LA': 'Louisiana',
    'ME': 'Maine', 'MD': 'Maryland', 'MA': 'Massachusetts', 'MI': 'Michigan',
    'MN': 'Minnesota', 'MS': 'Mississippi', 'MO': 'Missouri', 'MT': 'Montana',
    'NE': 'Nebraska', 'NV': 'Nevada', 'NH': 'New Hampshire', 'NJ': 'New Jersey',
    'NM': 'New Mexico', 'NY': 'New York', 'NC': 'North Carolina', 'ND': 'North Dakota',
    'OH': 'Ohio', 'OK': 'Oklahoma', 'OR': 'Oregon', 'PA': 'Pennsylvania',
    'RI': 'Rhode Island', 'SC': 'South Carolina', 'SD': 'South Dakota', 'TN': 'Tennessee',
    'TX': 'Texas', 'UT': 'Utah', 'VT': 'Vermont', 'VA': 'Virginia',
    'WA': 'Washington', 'WV': 'West Virginia', 'WI': 'Wisconsin', 'WY': 'Wyoming'
}

df["Location"]=df["Location"].apply(lambda x:', '.join([x.split(', ')[0],us_state_abbrev.get(x.upper().split(', ')[1],x.split(', ')[1])]) if len(x.split(', '))>1 else (x if x else ' ') )

In [86]:
df["Headquarters"]=df["Headquarters"].apply(lambda x:', '.join([x.split(', ')[0],us_state_abbrev.get(x.upper().split(', ')[1],x.split(', ')[1])]) if len(x.split(', '))>1 else (x if x else ' ') )
df=df.apply(lambda x:x.str.lower() if x.dtype=='object' else x)
df.tail()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Salary Type,Company ID
667,667,data scientist,105000-167000 (glassdoor est.),summary we’re looking for a data scientist to...,3.6,tranzact,"fort lee, new jersey","fort lee, new jersey",1001 to 5000 employees,1989,company - private,advertising & marketing,business services,unknown / non-applicable,-1,per year,432
668,668,data scientist,105000-167000 (glassdoor est.),job description become a thought leader within...,-1.0,jkgt,"san francisco, california",-1,-1,-1,-1,-1,-1,-1,-1,per year,433
669,669,data scientist,105000-167000 (glassdoor est.),join a thriving company that is changing the w...,-1.0,accesshope,"irwindale, california",-1,-1,-1,-1,-1,-1,-1,-1,per year,434
670,670,data scientist,105000-167000 (glassdoor est.),100 remote opportunity as an ainlp data scient...,5.0,chateck incorporated,"san francisco, california","santa clara, california",1 to 50 employees,-1,company - private,advertising & marketing,business services,$1 to $5 million (usd),-1,per year,435
671,671,data scientist,105000-167000 (glassdoor est.),description the data scientist will be part o...,2.7,1-800-flowers,"new york, new york","carle place, new york",1001 to 5000 employees,1976,company - public,wholesale,business services,$1 to $2 billion (usd),-1,per year,365

In [2]:
!pip install --upgrade --force-reinstall geocoder

Collecting geocoder
  Downloading geocoder-1.38.1-py2.py3-none-any.whl.metadata (14 kB)
Collecting click (from geocoder)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting future (from geocoder)
  Downloading future-1.0.0-py3-none-any.whl.metadata (4.0 kB)
Collecting ratelim (from geocoder)
  Downloading ratelim-0.1.6-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting requests (from geocoder)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting six (from geocoder)
  Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting colorama (from click->geocoder)
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting decorator (from ratelim->geocoder)
  Using cached decorator-5.1.1-py3-none-any.whl.metadata (4.0 kB)
Collecting charset-normalizer<4,>=2 (from requests->geocoder)
  Using cached charset_normalizer-3.4.0-cp312-cp312-win_amd64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests->geocoder)
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests->geocoder)
  Using cached urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests->geocoder)
  Using cached certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Downloading geocoder-1.38.1-py2.py3-none-any.whl (98 kB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Downloading future-1.0.0-py3-none-any.whl (491 kB)
Downloading ratelim-0.1.6-py2.py3-none-any.whl (4.0 kB)
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Using cached certifi-2024.8.30-py3-none-any.whl (167 kB)
Using cached charset_normalizer-3.4.0-cp312-cp312-win_amd64.whl (102 kB)
Using cached idna-3.10-py3-none-any.whl (70 kB)
Using cached urllib3-2.2.3-py3-none-any.whl (126 kB)
Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Installing collected packages: urllib3, six, idna, future, decorator, colorama, charset-normalizer, certifi, requests, ratelim, click, geocoder
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.2.2
    Uninstalling urllib3-2.2.2:
      Successfully uninstalled urllib3-2.2.2
  Attempting uninstall: six
    Found existing installation: six 1.16.0
    Uninstalling six-1.16.0:
      Successfully uninstalled six-1.16.0
  Attempting uninstall: idna
    Found existing installation: idna 3.7
    Uninstalling idna-3.7:
      Successfully uninstalled idna-3.7
  Attempting uninstall: decorator
    Found existing installation: decorator 5.1.1
    Uninstalling decorator-5.1.1:
      Successfully uninstalled decorator-5.1.1
  Attempting uninstall: colorama
    Found existing installation: colorama 0.4.6
    Uninstalling colorama-0.4.6:
      Successfully uninstalled colorama-0.4.6
  Attempting uninstall: charset-normalizer
    Found existing installation: charset-normalizer 3.3.2
    Uninstalling charset-normalizer-3.3.2:
      Successfully uninstalled charset-normalizer-3.3.2
  Attempting uninstall: certifi
    Found existing installation: certifi 2024.7.4
    Uninstalling certifi-2024.7.4:
      Successfully uninstalled certifi-2024.7.4
  Attempting uninstall: requests
    Found existing installation: requests 2.31.0
    Uninstalling requests-2.31.0:
      Successfully uninstalled requests-2.31.0
  Attempting uninstall: click
    Found existing installation: click 8.1.7
    Uninstalling click-8.1.7:
      Successfully uninstalled click-8.1.7
  Attempting uninstall: geocoder
    Found existing installation: geocoder 0.6.0
    Uninstalling geocoder-0.6.0:
      Successfully uninstalled geocoder-0.6.0
Successfully installed certifi-2024.8.30 charset-normalizer-3.4.0 click-8.1.7 colorama-0.4.6 decorator-5.1.1 future-1.0.0 geocoder-1.38.1 idna-3.10 ratelim-0.1.6 requests-2.32.3 six-1.16.0 urllib3-2.2.3

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\sebsn\AppData\Local\Programs\Python\Python312\Lib\site-packages\~harset_normalizer'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
arcgis 2.4.0 requires requests<2.32.0,>=2.30.0, but you have requests 2.32.3 which is incompatible.

In [36]:
#5
!pip install haversine
import geocoder
import haversine as hs
import time

def calculate_distance(row):
    location = row['Location']
    headquarters = row['Headquarters']

    # Geocode location and headquarters using ArcGIS
    try:
        location_coords = geocoder.arcgis(location, timeout=10).latlng
        time.sleep(1)  # Pause for 1 second between requests
        hq_coords = geocoder.arcgis(headquarters, timeout=10).latlng
    except Exception as e:
        print(f"Error geocoding {location} or {headquarters}: {e}")
        return None

    if location_coords and hq_coords:
        # Calculate distance using haversine formula (in miles)
        distance = hs.haversine(location_coords, hq_coords, unit=hs.Unit.MILES)
        return distance
    else:
        return None  # Handle cases where geocoding fails

# Apply distance calculation to the DataFrame
df['Distance'] = df.apply(calculate_distance, axis=1)

# Identify remote positions (e.g., distance > 50 miles)
df['Remote'] = df['Distance'] > 50

Requirement already satisfied: haversine in c:\users\sebsn\appdata\local\programs\python\python312\lib\site-packages (2.8.1)

In [14]:
df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Salary Type,Company ID,Distance,Remote
0,0,sr data scientist,137000-171000 (glassdoor est.),description the senior data scientist is resp...,3.1,healthfirst,"new york, new york","new york, new york",1001 to 5000 employees,1993,nonprofit organization,insurance carriers,insurance,unknown / non-applicable,"emblemhealth, unitedhealth group, aetna",per year,1,0.000000,False
1,1,data scientist,137000-171000 (glassdoor est.),"secure our nation, ignite your future join th...",4.2,mantech,"chantilly, virginia","herndon, virginia",5001 to 10000 employees,1968,company - public,research & development,business services,$1 to $2 billion (usd),-1,per year,2,5.884063,False
2,2,data scientist,137000-171000 (glassdoor est.),overview analysis group is one of the larges...,3.8,analysis group,"boston, massachusetts","boston, massachusetts",1001 to 5000 employees,1981,private practice / firm,consulting,business services,$100 to $500 million (usd),-1,per year,3,0.000000,False
3,3,data scientist,137000-171000 (glassdoor est.),job description: do you have a passion for da...,3.5,inficon,"newton, massachusetts","bad ragaz, switzerland",501 to 1000 employees,2000,company - public,electrical & electronic manufacturing,manufacturing,$100 to $500 million (usd),"mks instruments, pfeiffer vacuum, agilent tech...",per year,4,3798.189362,True
4,4,data scientist,137000-171000 (glassdoor est.),data scientist affinity solutions / marketing ...,2.9,affinity solutions,"new york, new york","new york, new york",51 to 200 employees,1998,company - private,advertising & marketing,business services,unknown / non-applicable,"commerce signals, cardlytics, yodlee",per year,5,0.000000,False

In [58]:
df["Remote"] = df["Remote"].apply(lambda x: "yes" if x else "no")
df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,Industry,Sector,Revenue,Competitors,Salary Type,Company ID,Distance,Remote,MinRevenue,MaxRevenue
0,0,sr data scientist,137000-171000 (glassdoor est.),description the senior data scientist is resp...,3.1,healthfirst,"new york, new york","new york, new york",1001 to 5000 employees,1993,...,insurance carriers,insurance,unknown / non-applicable,"emblemhealth, unitedhealth group, aetna",per year,1,0.000000,yes,nan,nan
1,1,data scientist,137000-171000 (glassdoor est.),"secure our nation, ignite your future join th...",4.2,mantech,"chantilly, virginia","herndon, virginia",5001 to 10000 employees,1968,...,research & development,business services,1,-1,per year,2,5.884063,yes,nan,nan
2,2,data scientist,137000-171000 (glassdoor est.),overview analysis group is one of the larges...,3.8,analysis group,"boston, massachusetts","boston, massachusetts",1001 to 5000 employees,1981,...,consulting,business services,100,-1,per year,3,0.000000,yes,nan,nan
3,3,data scientist,137000-171000 (glassdoor est.),job description: do you have a passion for da...,3.5,inficon,"newton, massachusetts","bad ragaz, switzerland",501 to 1000 employees,2000,...,electrical & electronic manufacturing,manufacturing,100,"mks instruments, pfeiffer vacuum, agilent tech...",per year,4,3798.189362,yes,nan,nan
4,4,data scientist,137000-171000 (glassdoor est.),data scientist affinity solutions / marketing ...,2.9,affinity solutions,"new york, new york","new york, new york",51 to 200 employees,1998,...,advertising & marketing,business services,unknown / non-applicable,"commerce signals, cardlytics, yodlee",per year,5,0.000000,yes,nan,nan

In [87]:
df["Revenue"] = df["Revenue"].str.replace("unknown / non-applicable", "", regex=True)

In [91]:
df.head(632)

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Salary Type,Company ID,MinRevenue,MaxRevenue
0,0,sr data scientist,137000-171000 (glassdoor est.),description the senior data scientist is resp...,3.1,healthfirst,"new york, new york","new york, new york",1001 to 5000 employees,1993,nonprofit organization,insurance carriers,insurance,,"emblemhealth, unitedhealth group, aetna",per year,1,NaN,NaN
1,1,data scientist,137000-171000 (glassdoor est.),"secure our nation, ignite your future join th...",4.2,mantech,"chantilly, virginia","herndon, virginia",5001 to 10000 employees,1968,company - public,research & development,business services,$1 to $2 billion (usd),-1,per year,2,1.0,2000.0
2,2,data scientist,137000-171000 (glassdoor est.),overview analysis group is one of the larges...,3.8,analysis group,"boston, massachusetts","boston, massachusetts",1001 to 5000 employees,1981,private practice / firm,consulting,business services,$100 to $500 million (usd),-1,per year,3,100.0,500.0
3,3,data scientist,137000-171000 (glassdoor est.),job description: do you have a passion for da...,3.5,inficon,"newton, massachusetts","bad ragaz, switzerland",501 to 1000 employees,2000,company - public,electrical & electronic manufacturing,manufacturing,$100 to $500 million (usd),"mks instruments, pfeiffer vacuum, agilent tech...",per year,4,100.0,500.0
4,4,data scientist,137000-171000 (glassdoor est.),data scientist affinity solutions / marketing ...,2.9,affinity solutions,"new york, new york","new york, new york",51 to 200 employees,1998,company - private,advertising & marketing,business services,,"commerce signals, cardlytics, yodlee",per year,5,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
627,627,data scientist,87000-141000 (glassdoor est.),job description data scientist location: the ...,4.6,murray resources,"the woodlands, texas","houston, texas",1 to 50 employees,1988,company - private,staffing & outsourcing,business services,$10 to $25 million (usd),-1,per year,348,10.0,25.0
628,628,data scientist,87000-141000 (glassdoor est.),"geotab, a global leader in iot and connected t...",4.3,geotab,"oakville, california","oakville, canada",1001 to 5000 employees,2000,company - private,computer hardware & software,information technology,$100 to $500 million (usd),-1,per year,415,100.0,500.0
629,629,data scientist,87000-141000 (glassdoor est.),job description data scientist duration: 6+ mo...,4.7,crs group,"chicago, illinois","itasca, illinois",51 to 200 employees,1994,company - private,staffing & outsourcing,business services,$10 to $25 million (usd),-1,per year,352,10.0,25.0
630,630,data scientist,87000-141000 (glassdoor est.),"eglobaltech, one of northern virginia’s fastes...",3.7,eglobaltech,"arlington, virginia","vienna, virginia",201 to 500 employees,2004,company - private,it services,information technology,,-1,per year,416,NaN,NaN
631,631,"data scientist, kinship - nyc/portland",92000-155000 (glassdoor est.),back to search results previous job next job ...,3.9,mars,"new york, new york","mc lean, virginia",10000+ employees,1911,company - private,food & beverage manufacturing,manufacturing,$10+ billion (usd),-1,per year,83,10000.0,10000.0

In [90]:
import re

def handle_specific_revenue_formats(revenue_str):
   
    pattern_mixed_range = r'\$(\d+([.,]\d+)?)\s*(million|billion)?\s*(to|-)\s*\$?(\d+([.,]\d+)?)?\s*(million|billion)?'
    match_mixed_range = re.search(pattern_mixed_range, str(revenue_str), re.IGNORECASE)

    if match_mixed_range:
        min_revenue = float(match_mixed_range.group(1).replace(',', ''))
        min_unit = match_mixed_range.group(3)
        max_revenue = float(match_mixed_range.group(5).replace(',', '')) if match_mixed_range.group(5) else min_revenue
        max_unit = match_mixed_range.group(7)

        
        if min_unit and min_unit.lower() == 'billion':
            min_revenue *= 1000
        if max_unit and max_unit.lower() == 'billion':
            max_revenue *= 1000

        return min_revenue, max_revenue

    
    pattern_plus_billion = r'\$(\d+)\+\s*billion'
    match_plus_billion = re.search(pattern_plus_billion, str(revenue_str), re.IGNORECASE)

    if match_plus_billion:
        min_revenue = float(match_plus_billion.group(1)) * 1000  
        return min_revenue, min_revenue  

    
    pattern_less_than_million = r'less than \$1 million'
    match_less_than_million = re.search(pattern_less_than_million, str(revenue_str), re.IGNORECASE)

    if match_less_than_million:
        return 0, 1  

  
    return float('nan'), float('nan')

df[['MinRevenue', 'MaxRevenue']] = df['Revenue'].apply(lambda x: pd.Series(handle_specific_revenue_formats(x)))

In [92]:
df["MinRevenue"] = df["MinRevenue"].astype(str).str.replace(r"\.0$", "k", regex=True)
df["MaxRevenue"] = df["MaxRevenue"].astype(str).str.replace(r"\.0$", "k", regex=True)
df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Salary Type,Company ID,MinRevenue,MaxRevenue
0,0,sr data scientist,137000-171000 (glassdoor est.),description the senior data scientist is resp...,3.1,healthfirst,"new york, new york","new york, new york",1001 to 5000 employees,1993,nonprofit organization,insurance carriers,insurance,,"emblemhealth, unitedhealth group, aetna",per year,1,nan,nan
1,1,data scientist,137000-171000 (glassdoor est.),"secure our nation, ignite your future join th...",4.2,mantech,"chantilly, virginia","herndon, virginia",5001 to 10000 employees,1968,company - public,research & development,business services,$1 to $2 billion (usd),-1,per year,2,1k,2000k
2,2,data scientist,137000-171000 (glassdoor est.),overview analysis group is one of the larges...,3.8,analysis group,"boston, massachusetts","boston, massachusetts",1001 to 5000 employees,1981,private practice / firm,consulting,business services,$100 to $500 million (usd),-1,per year,3,100k,500k
3,3,data scientist,137000-171000 (glassdoor est.),job description: do you have a passion for da...,3.5,inficon,"newton, massachusetts","bad ragaz, switzerland",501 to 1000 employees,2000,company - public,electrical & electronic manufacturing,manufacturing,$100 to $500 million (usd),"mks instruments, pfeiffer vacuum, agilent tech...",per year,4,100k,500k
4,4,data scientist,137000-171000 (glassdoor est.),data scientist affinity solutions / marketing ...,2.9,affinity solutions,"new york, new york","new york, new york",51 to 200 employees,1998,company - private,advertising & marketing,business services,,"commerce signals, cardlytics, yodlee",per year,5,nan,nan

In [93]:
df["MinRevenue"] = df["MinRevenue"].astype(str).str.replace("k", "m", regex=True)
df["MaxRevenue"] = df["MaxRevenue"].astype(str).str.replace("k", "m", regex=True)
df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Salary Type,Company ID,MinRevenue,MaxRevenue
0,0,sr data scientist,137000-171000 (glassdoor est.),description the senior data scientist is resp...,3.1,healthfirst,"new york, new york","new york, new york",1001 to 5000 employees,1993,nonprofit organization,insurance carriers,insurance,,"emblemhealth, unitedhealth group, aetna",per year,1,nan,nan
1,1,data scientist,137000-171000 (glassdoor est.),"secure our nation, ignite your future join th...",4.2,mantech,"chantilly, virginia","herndon, virginia",5001 to 10000 employees,1968,company - public,research & development,business services,$1 to $2 billion (usd),-1,per year,2,1m,2000m
2,2,data scientist,137000-171000 (glassdoor est.),overview analysis group is one of the larges...,3.8,analysis group,"boston, massachusetts","boston, massachusetts",1001 to 5000 employees,1981,private practice / firm,consulting,business services,$100 to $500 million (usd),-1,per year,3,100m,500m
3,3,data scientist,137000-171000 (glassdoor est.),job description: do you have a passion for da...,3.5,inficon,"newton, massachusetts","bad ragaz, switzerland",501 to 1000 employees,2000,company - public,electrical & electronic manufacturing,manufacturing,$100 to $500 million (usd),"mks instruments, pfeiffer vacuum, agilent tech...",per year,4,100m,500m
4,4,data scientist,137000-171000 (glassdoor est.),data scientist affinity solutions / marketing ...,2.9,affinity solutions,"new york, new york","new york, new york",51 to 200 employees,1998,company - private,advertising & marketing,business services,,"commerce signals, cardlytics, yodlee",per year,5,nan,nan

6. Missing Data Handling:
• Fill Missing Values in Categorical Columns: Fill missing values
in columns such as ”Industry” and ”Sector.”
• Fill Missing Values in Rating: Fill missing values in ”Rating.”
7. Cleaning and Extracting Data from ”Job Description”:
• Length Calculation: Create a column to calculate the word count
or character length of each ”Job Description” to help filter lengthy
descriptions.
• Remote Work Flag: Identify if the job allows remote work by
checking for keywords (like ”remote,” ”telecommute”) in the ”Job
Description”.

• Experience Level Parsing: Add columns to identify required ex-
perience levels (e.g., ”entry level,” ”5+ years”) by parsing ”Job De-
scription.”

8. Additional Column Standardization:
• Numeric Conversion of Founding Year: Ensure ”Founded” is a
numeric column, and set a minimum year threshold (e.g., 1800) to
filter out any erroneous entries.
• Size Categorization: For ”Size,” create size categories (e.g.,
”small,” ”medium,” ”large”) based on ranges in employee count.
9. Outlier Detection and Handling:

• Salary Outliers: Detect outliers in the salary range and flag unusu-
ally high or low salary estimates for each job title.

• Rating Outliers: Identify extreme ratings (e.g., below 2.0 or above
4.5) and flag them to verify their accuracy.

• Founded Year Outliers: Flag companies with founding years out-
side a realistic range as potential data entry errors.

10. Column Optimization and Data Type Conversion:
• Convert Numerical Columns: Ensure columns like ”Rating” and
”Founded” are in a suitable numeric format (int64 or float64) and
convert others as appropriate.

• Memory Optimization: Downcast numeric columns (e.g., ”Rat-
ing,” ”Founded”) to the smallest integer or float type without data

loss to optimize memory usage.

In [100]:
import numpy as np 

df['Revenue'].fillna(value=np.nan, inplace=True) 
df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Salary Type,Company ID,MinRevenue,MaxRevenue
0,0,sr data scientist,137000-171000 (glassdoor est.),description the senior data scientist is resp...,3.1,healthfirst,"new york, new york","new york, new york",1001 to 5000 employees,1993,nonprofit organization,insurance carriers,insurance,,"emblemhealth, unitedhealth group, aetna",per year,1,nan,nan
1,1,data scientist,137000-171000 (glassdoor est.),"secure our nation, ignite your future join th...",4.2,mantech,"chantilly, virginia","herndon, virginia",5001 to 10000 employees,1968,company - public,research & development,business services,$1 to $2 billion (usd),-1,per year,2,1m,2000m
2,2,data scientist,137000-171000 (glassdoor est.),overview analysis group is one of the larges...,3.8,analysis group,"boston, massachusetts","boston, massachusetts",1001 to 5000 employees,1981,private practice / firm,consulting,business services,$100 to $500 million (usd),-1,per year,3,100m,500m
3,3,data scientist,137000-171000 (glassdoor est.),job description: do you have a passion for da...,3.5,inficon,"newton, massachusetts","bad ragaz, switzerland",501 to 1000 employees,2000,company - public,electrical & electronic manufacturing,manufacturing,$100 to $500 million (usd),"mks instruments, pfeiffer vacuum, agilent tech...",per year,4,100m,500m
4,4,data scientist,137000-171000 (glassdoor est.),data scientist affinity solutions / marketing ...,2.9,affinity solutions,"new york, new york","new york, new york",51 to 200 employees,1998,company - private,advertising & marketing,business services,,"commerce signals, cardlytics, yodlee",per year,5,nan,nan

In [113]:

df.head(632)

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Salary Type,Company ID,MinRevenue,MaxRevenue
0,0,sr data scientist,137000-171000 (glassdoor est.),description the senior data scientist is resp...,3.1,healthfirst,"new york, new york","new york, new york",1001 to 5000 employees,1993,nonprofit organization,insurance carriers,insurance,,"emblemhealth, unitedhealth group, aetna",per year,1,nan,nan
1,1,data scientist,137000-171000 (glassdoor est.),"secure our nation, ignite your future join th...",4.2,mantech,"chantilly, virginia","herndon, virginia",5001 to 10000 employees,1968,company - public,research & development,business services,$1 to $2 billion (usd),-1,per year,2,1m,2000m
2,2,data scientist,137000-171000 (glassdoor est.),overview analysis group is one of the larges...,3.8,analysis group,"boston, massachusetts","boston, massachusetts",1001 to 5000 employees,1981,private practice / firm,consulting,business services,$100 to $500 million (usd),-1,per year,3,100m,500m
3,3,data scientist,137000-171000 (glassdoor est.),job description: do you have a passion for da...,3.5,inficon,"newton, massachusetts","bad ragaz, switzerland",501 to 1000 employees,2000,company - public,electrical & electronic manufacturing,manufacturing,$100 to $500 million (usd),"mks instruments, pfeiffer vacuum, agilent tech...",per year,4,100m,500m
4,4,data scientist,137000-171000 (glassdoor est.),data scientist affinity solutions / marketing ...,2.9,affinity solutions,"new york, new york","new york, new york",51 to 200 employees,1998,company - private,advertising & marketing,business services,,"commerce signals, cardlytics, yodlee",per year,5,nan,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
627,627,data scientist,87000-141000 (glassdoor est.),job description data scientist location: the ...,4.6,murray resources,"the woodlands, texas","houston, texas",1 to 50 employees,1988,company - private,staffing & outsourcing,business services,$10 to $25 million (usd),-1,per year,348,10m,25m
628,628,data scientist,87000-141000 (glassdoor est.),"geotab, a global leader in iot and connected t...",4.3,geotab,"oakville, california","oakville, canada",1001 to 5000 employees,2000,company - private,computer hardware & software,information technology,$100 to $500 million (usd),-1,per year,415,100m,500m
629,629,data scientist,87000-141000 (glassdoor est.),job description data scientist duration: 6+ mo...,4.7,crs group,"chicago, illinois","itasca, illinois",51 to 200 employees,1994,company - private,staffing & outsourcing,business services,$10 to $25 million (usd),-1,per year,352,10m,25m
630,630,data scientist,87000-141000 (glassdoor est.),"eglobaltech, one of northern virginia’s fastes...",3.7,eglobaltech,"arlington, virginia","vienna, virginia",201 to 500 employees,2004,company - private,it services,information technology,,-1,per year,416,nan,nan
631,631,"data scientist, kinship - nyc/portland",92000-155000 (glassdoor est.),back to search results previous job next job ...,3.9,mars,"new york, new york","mc lean, virginia",10000+ employees,1911,company - private,food & beverage manufacturing,manufacturing,$10+ billion (usd),-1,per year,83,10000m,10000m

In [112]:
#6
empty_values = df[df["Rating"] == ""]

numeric_values = df[pd.to_numeric(df["Rating"], errors='coerce').notnull()]

unknown_values = df[df["Rating"].isnull()]

all_problematic_values = pd.concat([empty_values, numeric_values, unknown_values])
print(all_problematic_values["Rating"].unique())

[ 3.1  4.2  3.8  3.5  2.9  3.9  4.4  3.6  4.5  4.7  3.7  3.4  4.1  3.2
  4.3  2.8  5.   4.8  3.3  2.7  2.2  2.6  4.   2.5  4.9  2.4 -1.   2.3
  4.6  3.   2.1  2. ]

In [98]:
df['Sector'] = df['Sector'].fillna('nan')
df['Industry'] = df['Industry'].fillna('nan')
df['Rating'] = df['Rating'].fillna('nan')

In [102]:
df["Rating"] = df["Rating"].apply(lambda x: str(x).replace(".","",1) if str(x).endswith(".") and str(x)[:-1].isdigit() else x)

In [111]:

df["Rating"] = df["Rating"].apply(lambda x: str(x).replace("-","",1) if str(x).startswith(".") and str(x)[:-1].isdigit() else x)

In [114]:
#7
df['Job Description Length (Words)'] = df['Job Description'].apply(lambda x: len(str(x).split()))
df['Job Description Length (Characters)'] = df['Job Description'].apply(lambda x: len(str(x)))

In [124]:
df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,Industry,Sector,Revenue,Competitors,Salary Type,Company ID,MinRevenue,MaxRevenue,Job Description Length (Words),Job Description Length (Characters)
0,0,sr data scientist,137000-171000 (glassdoor est.),description the senior data scientist is resp...,3.1,healthfirst,"new york, new york","new york, new york",1001 to 5000 employees,1993,...,insurance carriers,insurance,,"emblemhealth, unitedhealth group, aetna",per year,1,nan,nan,469,3389
1,1,data scientist,137000-171000 (glassdoor est.),"secure our nation, ignite your future join th...",4.2,mantech,"chantilly, virginia","herndon, virginia",5001 to 10000 employees,1968,...,research & development,business services,$1 to $2 billion (usd),-1,per year,2,1m,2000m,542,4076
2,2,data scientist,137000-171000 (glassdoor est.),overview analysis group is one of the larges...,3.8,analysis group,"boston, massachusetts","boston, massachusetts",1001 to 5000 employees,1981,...,consulting,business services,$100 to $500 million (usd),-1,per year,3,100m,500m,1262,8749
3,3,data scientist,137000-171000 (glassdoor est.),job description: do you have a passion for da...,3.5,inficon,"newton, massachusetts","bad ragaz, switzerland",501 to 1000 employees,2000,...,electrical & electronic manufacturing,manufacturing,$100 to $500 million (usd),"mks instruments, pfeiffer vacuum, agilent tech...",per year,4,100m,500m,452,3349
4,4,data scientist,137000-171000 (glassdoor est.),data scientist affinity solutions / marketing ...,2.9,affinity solutions,"new york, new york","new york, new york",51 to 200 employees,1998,...,advertising & marketing,business services,,"commerce signals, cardlytics, yodlee",per year,5,nan,nan,378,2728

In [120]:
filtered_words = df[df['Job Description Length (Words)'] < 500]
filtered_words

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,Industry,Sector,Revenue,Competitors,Salary Type,Company ID,MinRevenue,MaxRevenue,Job Description Length (Words),Job Description Length (Characters)
0,0,sr data scientist,137000-171000 (glassdoor est.),description the senior data scientist is resp...,3.1,healthfirst,"new york, new york","new york, new york",1001 to 5000 employees,1993,...,insurance carriers,insurance,,"emblemhealth, unitedhealth group, aetna",per year,1,nan,nan,469,3389
3,3,data scientist,137000-171000 (glassdoor est.),job description: do you have a passion for da...,3.5,inficon,"newton, massachusetts","bad ragaz, switzerland",501 to 1000 employees,2000,...,electrical & electronic manufacturing,manufacturing,$100 to $500 million (usd),"mks instruments, pfeiffer vacuum, agilent tech...",per year,4,100m,500m,452,3349
4,4,data scientist,137000-171000 (glassdoor est.),data scientist affinity solutions / marketing ...,2.9,affinity solutions,"new york, new york","new york, new york",51 to 200 employees,1998,...,advertising & marketing,business services,,"commerce signals, cardlytics, yodlee",per year,5,nan,nan,378,2728
7,7,data scientist,137000-171000 (glassdoor est.),introduction have you always wanted to run ex...,3.5,irobot,"bedford, massachusetts","bedford, massachusetts",1001 to 5000 employees,1990,...,consumer electronics & appliances stores,retail,$1 to $2 billion (usd),-1,per year,8,1m,2000m,250,1736
8,8,staff data scientist - analytics,137000-171000 (glassdoor est.),intuit is seeking a staff data scientist to co...,4.4,intuit - data,"san diego, california","mountain view, california",5001 to 10000 employees,1983,...,computer hardware & software,information technology,$2 to $5 billion (usd),"square, paypal, h&r block",per year,9,2m,5000m,68,456
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
665,665,data scientist,105000-167000 (glassdoor est.),criterion systems seeks a data scientist to su...,3.8,"criterion systems, inc.","vienna, virginia","vienna, virginia",201 to 500 employees,2005,...,it services,information technology,$50 to $100 million (usd),-1,per year,430,50m,100m,344,2667
668,668,data scientist,105000-167000 (glassdoor est.),job description become a thought leader within...,-1.0,jkgt,"san francisco, california",-1,-1,-1,...,-1,-1,-1,-1,per year,433,nan,nan,162,1251
669,669,data scientist,105000-167000 (glassdoor est.),join a thriving company that is changing the w...,-1.0,accesshope,"irwindale, california",-1,-1,-1,...,-1,-1,-1,-1,per year,434,nan,nan,393,2793
670,670,data scientist,105000-167000 (glassdoor est.),100 remote opportunity as an ainlp data scient...,5.0,chateck incorporated,"san francisco, california","santa clara, california",1 to 50 employees,-1,...,advertising & marketing,business services,$1 to $5 million (usd),-1,per year,435,1m,5m,455,3426
671,671,data scientist,105000-167000 (glassdoor est.),description the data scientist will be part o...,2.7,1-800-flowers,"new york, new york","carle place, new york",1001 to 5000 employees,1976,...,wholesale,business services,$1 to $2 billion (usd),-1,per year,365,1m,2000m,421,3000

In [150]:
remote_work = df.apply(lambda x: x["Company ID"] if "remote" in x["Job Description"] else None, axis=1)
remote_work.dropna(inplace=True)
remote_work

14      15.0
17      18.0
34      33.0
53      52.0
70      67.0
       ...
654    359.0
655    361.0
667    432.0
670    435.0
671    365.0
Length: 63, dtype: float64

In [172]:
import re

df["Experience Level"] = df["Job Description"].apply(lambda x: \
    "entry level" if re.search(r"(entry\s?level|junior|graduate)", x, re.IGNORECASE) else \
    "mid level" if re.search(r"(mid\s?level|intermediate|3-5\s?years|3\+? years|4-6\s?years|4\+? years|5-7\s?years|5\+? years)", x, re.IGNORECASE) else \
    "senior level" if re.search(r"(senior|lead|principal|manager|director|executive|7\+? years|8\+? years|9\+? years|10\+? years)", x, re.IGNORECASE) else \
    "Unknown")

In [173]:
df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,Sector,Revenue,Competitors,Salary Type,Company ID,MinRevenue,MaxRevenue,Job Description Length (Words),Job Description Length (Characters),Experience Level
0,0,sr data scientist,137000-171000 (glassdoor est.),description the senior data scientist is resp...,3.1,healthfirst,"new york, new york","new york, new york",1001 to 5000 employees,1993,...,insurance,,"emblemhealth, unitedhealth group, aetna",per year,1,nan,nan,469,3389,senior level
1,1,data scientist,137000-171000 (glassdoor est.),"secure our nation, ignite your future join th...",4.2,mantech,"chantilly, virginia","herndon, virginia",5001 to 10000 employees,1968,...,business services,$1 to $2 billion (usd),-1,per year,2,1m,2000m,542,4076,mid level
2,2,data scientist,137000-171000 (glassdoor est.),overview analysis group is one of the larges...,3.8,analysis group,"boston, massachusetts","boston, massachusetts",1001 to 5000 employees,1981,...,business services,$100 to $500 million (usd),-1,per year,3,100m,500m,1262,8749,senior level
3,3,data scientist,137000-171000 (glassdoor est.),job description: do you have a passion for da...,3.5,inficon,"newton, massachusetts","bad ragaz, switzerland",501 to 1000 employees,2000,...,manufacturing,$100 to $500 million (usd),"mks instruments, pfeiffer vacuum, agilent tech...",per year,4,100m,500m,452,3349,Unknown
4,4,data scientist,137000-171000 (glassdoor est.),data scientist affinity solutions / marketing ...,2.9,affinity solutions,"new york, new york","new york, new york",51 to 200 employees,1998,...,business services,,"commerce signals, cardlytics, yodlee",per year,5,nan,nan,378,2728,senior level