In [206]:
import pandas as pd
df = pd.read_csv("DS-jobs.csv")

Data Cleaning and Preprocessing

In [207]:
df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Sr Data Scientist,$137K-$171K (Glassdoor est.),Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna"
1,1,Data Scientist,$137K-$171K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1
2,2,Data Scientist,$137K-$171K (Glassdoor est.),Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,$137K-$171K (Glassdoor est.),JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech..."
4,4,Data Scientist,$137K-$171K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

Data Cleaning and Preprocessing
1. Detailed Parsing of Salary Information:

• Remove Currency Symbols: Remove ”$” or other currency sym-
bols from ”Salary Estimate” to simplify the salary parsing process.

• Salary Type Extraction: Create a column that identifies whether

the salary is presented as ”per year,” ”per hour,” etc., based on com-
mon indicators in ”Salary Estimate.”

2. Handle Special Characters in Text Columns:
• Text Standardization: Remove or replace special characters (e.g.,
”\n”, ”\t”, and other symbols) from columns like ”Job Description”
and ”Company Name” for consistency.

• Lowercasing: Convert all text columns (e.g., ”Job Title,” ”Com-
pany Name,” ”Industry”) to lowercase to standardize the format and

avoid case sensitivity issues during analysis.
3. Company Name Refinement:
• Remove Rating from Company Name: Clean up ”Company
Name” by removing any appended rating values (e.g., ”Company
Name\n3.8”).
• Unique Company Identifier: Generate a unique identifier for each

company based on the cleaned ”Company Name” to help with com-
parisons.

4. Standardizing Location Data:
• Expand State Abbreviations: For the ”Location” column, expand
state abbreviations (e.g., ”CA” → ”California”) to ensure uniformity.

• Location Format Consistency: Check for any inconsistent for-
mats in ”Location” and ”Headquarters” and standardize to ”City,

State” format.
• Distance Calculation: If city and state information are available,
create approximate distance calculations between ”Location” and
”Headquarters” to identify remote positions.
5. Revenue Column Parsing and Cleaning:
• Extract Revenue Range: For each value in ”Revenue,” extract
minimum and maximum revenue values to separate columns.
• Currency Standardization: Ensure all revenue values are in the

same currency (e.g., USD) and handle conversions if any foreign cur-
rencies are detected.

• Fill Missing Values in Revenue: Fill missing values in the ”Rev-
enue” column.

In [208]:

df['Salary Type'] = df['Salary Estimate'].apply(lambda x: 'per hour' if 'per hour' in x.lower() else ('per year' if 'per year' in x.lower() else ('per day' if 'per day' in x.lower() else 'per year')))
df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Salary Type
0,0,Sr Data Scientist,$137K-$171K (Glassdoor est.),Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",per year
1,1,Data Scientist,$137K-$171K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,per year
2,2,Data Scientist,$137K-$171K (Glassdoor est.),Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1,per year
3,3,Data Scientist,$137K-$171K (Glassdoor est.),JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",per year
4,4,Data Scientist,$137K-$171K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",per year

In [209]:
#1
df['Salary Estimate'] = df['Salary Estimate'].str.replace('[£$€₹]', '',regex=True)
df['Salary Estimate']=df['Salary Estimate'].str.replace("K","000")

df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Salary Type
0,0,Sr Data Scientist,137000-171000 (Glassdoor est.),Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",per year
1,1,Data Scientist,137000-171000 (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,per year
2,2,Data Scientist,137000-171000 (Glassdoor est.),Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1,per year
3,3,Data Scientist,137000-171000 (Glassdoor est.),JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",per year
4,4,Data Scientist,137000-171000 (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",per year

In [210]:


#2
import re
def remove_special_char(Text):
  cleaned_text=re.sub(r"[^a-zA-Z0-9]","",Text)
  cleaned_text=re.sub(r"\s+","",cleaned_text)
  return cleaned_text


  df["Job Description"]=df["Job Description"].apply(remove_special_char)


  df["Company Name"]=df["Company Name"].apply(remove_special_char)

In [6]:
  df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Salary Type
0,0,Sr Data Scientist,137000-171000 (Glassdoor est.),Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",per year
1,1,Data Scientist,137000-171000 (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,per year
2,2,Data Scientist,137000-171000 (Glassdoor est.),Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1,per year
3,3,Data Scientist,137000-171000 (Glassdoor est.),JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",per year
4,4,Data Scientist,137000-171000 (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",per year

In [211]:
df["Job Description"]=df["Job Description"].str.replace("\n",' ',regex=True).str.replace("\t","",regex=True).str.replace("\r","",regex=True)
df["Company Name"]=df["Company Name"].str.replace("\n",' ',regex=True).str.replace("\t","",regex=True).str.replace("\r","",regex=True)
df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Salary Type
0,0,Sr Data Scientist,137000-171000 (Glassdoor est.),Description The Senior Data Scientist is resp...,3.1,Healthfirst 3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",per year
1,1,Data Scientist,137000-171000 (Glassdoor est.),"Secure our Nation, Ignite your Future Join th...",4.2,ManTech 4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,per year
2,2,Data Scientist,137000-171000 (Glassdoor est.),Overview Analysis Group is one of the larges...,3.8,Analysis Group 3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1,per year
3,3,Data Scientist,137000-171000 (Glassdoor est.),JOB DESCRIPTION: Do you have a passion for Da...,3.5,INFICON 3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",per year
4,4,Data Scientist,137000-171000 (Glassdoor est.),Data Scientist Affinity Solutions / Marketing ...,2.9,Affinity Solutions 2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",per year

In [212]:
df=df.apply(lambda x:x.str.lower() if x.dtype=='object' else x)
df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Salary Type
0,0,sr data scientist,137000-171000 (glassdoor est.),description the senior data scientist is resp...,3.1,healthfirst 3.1,"new york, ny","new york, ny",1001 to 5000 employees,1993,nonprofit organization,insurance carriers,insurance,unknown / non-applicable,"emblemhealth, unitedhealth group, aetna",per year
1,1,data scientist,137000-171000 (glassdoor est.),"secure our nation, ignite your future join th...",4.2,mantech 4.2,"chantilly, va","herndon, va",5001 to 10000 employees,1968,company - public,research & development,business services,$1 to $2 billion (usd),-1,per year
2,2,data scientist,137000-171000 (glassdoor est.),overview analysis group is one of the larges...,3.8,analysis group 3.8,"boston, ma","boston, ma",1001 to 5000 employees,1981,private practice / firm,consulting,business services,$100 to $500 million (usd),-1,per year
3,3,data scientist,137000-171000 (glassdoor est.),job description: do you have a passion for da...,3.5,inficon 3.5,"newton, ma","bad ragaz, switzerland",501 to 1000 employees,2000,company - public,electrical & electronic manufacturing,manufacturing,$100 to $500 million (usd),"mks instruments, pfeiffer vacuum, agilent tech...",per year
4,4,data scientist,137000-171000 (glassdoor est.),data scientist affinity solutions / marketing ...,2.9,affinity solutions 2.9,"new york, ny","new york, ny",51 to 200 employees,1998,company - private,advertising & marketing,business services,unknown / non-applicable,"commerce signals, cardlytics, yodlee",per year

In [213]:
#3
df["Company Name"] = df.apply(lambda x: x["Company Name"].replace(str(x["Rating"]), "", 1) if str(x["Rating"]) in x["Company Name"] else x["Company Name"], axis=1)

In [214]:
company_ids = {}
def create_company_id(company_name):
  if company_name not in company_ids:
    company_ids[company_name]=len(company_ids)+1
  return company_ids[company_name]

In [215]:
df["Company ID"]=df["Company Name"].apply(create_company_id)
df.tail()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Salary Type,Company ID
667,667,data scientist,105000-167000 (glassdoor est.),summary we’re looking for a data scientist to...,3.6,tranzact,"fort lee, nj","fort lee, nj",1001 to 5000 employees,1989,company - private,advertising & marketing,business services,unknown / non-applicable,-1,per year,432
668,668,data scientist,105000-167000 (glassdoor est.),job description become a thought leader within...,-1.0,jkgt,"san francisco, ca",-1,-1,-1,-1,-1,-1,-1,-1,per year,433
669,669,data scientist,105000-167000 (glassdoor est.),join a thriving company that is changing the w...,-1.0,accesshope,"irwindale, ca",-1,-1,-1,-1,-1,-1,-1,-1,per year,434
670,670,data scientist,105000-167000 (glassdoor est.),100 remote opportunity as an ainlp data scient...,5.0,chateck incorporated,"san francisco, ca","santa clara, ca",1 to 50 employees,-1,company - private,advertising & marketing,business services,$1 to $5 million (usd),-1,per year,435
671,671,data scientist,105000-167000 (glassdoor est.),description the data scientist will be part o...,2.7,1-800-flowers,"new york, ny","carle place, ny",1001 to 5000 employees,1976,company - public,wholesale,business services,$1 to $2 billion (usd),-1,per year,365

In [216]:
#4
us_state_abbrev = {
    'AL': 'Alabama', 'AK': 'Alaska', 'AZ': 'Arizona', 'AR': 'Arkansas', 'CA': 'California',
    'CO': 'Colorado', 'CT': 'Connecticut', 'DE': 'Delaware', 'DC': 'District of Columbia',
    'FL': 'Florida', 'GA': 'Georgia', 'HI': 'Hawaii', 'ID': 'Idaho', 'IL': 'Illinois',
    'IN': 'Indiana', 'IA': 'Iowa', 'KS': 'Kansas', 'KY': 'Kentucky', 'LA': 'Louisiana',
    'ME': 'Maine', 'MD': 'Maryland', 'MA': 'Massachusetts', 'MI': 'Michigan',
    'MN': 'Minnesota', 'MS': 'Mississippi', 'MO': 'Missouri', 'MT': 'Montana',
    'NE': 'Nebraska', 'NV': 'Nevada', 'NH': 'New Hampshire', 'NJ': 'New Jersey',
    'NM': 'New Mexico', 'NY': 'New York', 'NC': 'North Carolina', 'ND': 'North Dakota',
    'OH': 'Ohio', 'OK': 'Oklahoma', 'OR': 'Oregon', 'PA': 'Pennsylvania',
    'RI': 'Rhode Island', 'SC': 'South Carolina', 'SD': 'South Dakota', 'TN': 'Tennessee',
    'TX': 'Texas', 'UT': 'Utah', 'VT': 'Vermont', 'VA': 'Virginia',
    'WA': 'Washington', 'WV': 'West Virginia', 'WI': 'Wisconsin', 'WY': 'Wyoming'
}

df["Location"]=df["Location"].apply(lambda x:', '.join([x.split(', ')[0],us_state_abbrev.get(x.upper().split(', ')[1],x.split(', ')[1])]) if len(x.split(', '))>1 else (x if x else ' ') )

In [217]:
df["Headquarters"]=df["Headquarters"].apply(lambda x:', '.join([x.split(', ')[0],us_state_abbrev.get(x.upper().split(', ')[1],x.split(', ')[1])]) if len(x.split(', '))>1 else (x if x else ' ') )
df=df.apply(lambda x:x.str.lower() if x.dtype=='object' else x)
df.tail()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Salary Type,Company ID
667,667,data scientist,105000-167000 (glassdoor est.),summary we’re looking for a data scientist to...,3.6,tranzact,"fort lee, new jersey","fort lee, new jersey",1001 to 5000 employees,1989,company - private,advertising & marketing,business services,unknown / non-applicable,-1,per year,432
668,668,data scientist,105000-167000 (glassdoor est.),job description become a thought leader within...,-1.0,jkgt,"san francisco, california",-1,-1,-1,-1,-1,-1,-1,-1,per year,433
669,669,data scientist,105000-167000 (glassdoor est.),join a thriving company that is changing the w...,-1.0,accesshope,"irwindale, california",-1,-1,-1,-1,-1,-1,-1,-1,per year,434
670,670,data scientist,105000-167000 (glassdoor est.),100 remote opportunity as an ainlp data scient...,5.0,chateck incorporated,"san francisco, california","santa clara, california",1 to 50 employees,-1,company - private,advertising & marketing,business services,$1 to $5 million (usd),-1,per year,435
671,671,data scientist,105000-167000 (glassdoor est.),description the data scientist will be part o...,2.7,1-800-flowers,"new york, new york","carle place, new york",1001 to 5000 employees,1976,company - public,wholesale,business services,$1 to $2 billion (usd),-1,per year,365

In [14]:
!pip install --upgrade --force-reinstall geocoder

Collecting geocoder
  Using cached geocoder-1.38.1-py2.py3-none-any.whl.metadata (14 kB)
Collecting click (from geocoder)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting future (from geocoder)
  Using cached future-1.0.0-py3-none-any.whl.metadata (4.0 kB)
Collecting ratelim (from geocoder)
  Using cached ratelim-0.1.6-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting requests (from geocoder)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting six (from geocoder)
  Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting colorama (from click->geocoder)
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting decorator (from ratelim->geocoder)
  Using cached decorator-5.1.1-py3-none-any.whl.metadata (4.0 kB)
Collecting charset-normalizer<4,>=2 (from requests->geocoder)
  Using cached charset_normalizer-3.4.0-cp312-cp312-win_amd64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests->geocoder)
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests->geocoder)
  Using cached urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests->geocoder)
  Using cached certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Using cached geocoder-1.38.1-py2.py3-none-any.whl (98 kB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Using cached future-1.0.0-py3-none-any.whl (491 kB)
Using cached ratelim-0.1.6-py2.py3-none-any.whl (4.0 kB)
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Using cached certifi-2024.8.30-py3-none-any.whl (167 kB)
Using cached charset_normalizer-3.4.0-cp312-cp312-win_amd64.whl (102 kB)
Using cached idna-3.10-py3-none-any.whl (70 kB)
Using cached urllib3-2.2.3-py3-none-any.whl (126 kB)
Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Installing collected packages: urllib3, six, idna, future, decorator, colorama, charset-normalizer, certifi, requests, ratelim, click, geocoder
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.2.3
    Uninstalling urllib3-2.2.3:
      Successfully uninstalled urllib3-2.2.3
  Attempting uninstall: six
    Found existing installation: six 1.16.0
    Uninstalling six-1.16.0:
      Successfully uninstalled six-1.16.0
  Attempting uninstall: idna
    Found existing installation: idna 3.10
    Uninstalling idna-3.10:
      Successfully uninstalled idna-3.10
  Attempting uninstall: future
    Found existing installation: future 1.0.0
    Uninstalling future-1.0.0:
      Successfully uninstalled future-1.0.0
  Attempting uninstall: decorator
    Found existing installation: decorator 5.1.1
    Uninstalling decorator-5.1.1:
      Successfully uninstalled decorator-5.1.1
  Attempting uninstall: colorama
    Found existing installation: colorama 0.4.6
    Uninstalling colorama-0.4.6:
      Successfully uninstalled colorama-0.4.6
  Attempting uninstall: charset-normalizer
    Found existing installation: charset-normalizer 3.4.0
    Uninstalling charset-normalizer-3.4.0:
      Successfully uninstalled charset-normalizer-3.4.0
  Attempting uninstall: certifi
    Found existing installation: certifi 2024.8.30
    Uninstalling certifi-2024.8.30:
      Successfully uninstalled certifi-2024.8.30
  Attempting uninstall: requests
    Found existing installation: requests 2.32.3
    Uninstalling requests-2.32.3:
      Successfully uninstalled requests-2.32.3
  Attempting uninstall: ratelim
    Found existing installation: ratelim 0.1.6
    Uninstalling ratelim-0.1.6:
      Successfully uninstalled ratelim-0.1.6
  Attempting uninstall: click
    Found existing installation: click 8.1.7
    Uninstalling click-8.1.7:
      Successfully uninstalled click-8.1.7
  Attempting uninstall: geocoder
    Found existing installation: geocoder 1.38.1
    Uninstalling geocoder-1.38.1:
      Successfully uninstalled geocoder-1.38.1
Successfully installed certifi-2024.8.30 charset-normalizer-3.4.0 click-8.1.7 colorama-0.4.6 decorator-5.1.1 future-1.0.0 geocoder-1.38.1 idna-3.10 ratelim-0.1.6 requests-2.32.3 six-1.16.0 urllib3-2.2.3

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
arcgis 2.4.0 requires requests<2.32.0,>=2.30.0, but you have requests 2.32.3 which is incompatible.

In [15]:
#5
!pip install haversine
import geocoder
import haversine as hs
import time

def calculate_distance(row):
    location = row['Location']
    headquarters = row['Headquarters']

    
    try:
        location_coords = geocoder.arcgis(location, timeout=10).latlng
        time.sleep(1)  
        hq_coords = geocoder.arcgis(headquarters, timeout=10).latlng
    except Exception as e:
        print(f"Error geocoding {location} or {headquarters}: {e}")
        return None

    if location_coords and hq_coords:
       
        distance = hs.haversine(location_coords, hq_coords, unit=hs.Unit.MILES)
        return distance
    else:
        return None  


df['Distance'] = df.apply(calculate_distance, axis=1)


df['Remote'] = df['Distance'] > 50

Requirement already satisfied: haversine in c:\users\sebsn\appdata\local\programs\python\python312\lib\site-packages (2.8.1)

In [16]:
df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Salary Type,Company ID,Distance,Remote
0,0,sr data scientist,137000-171000 (glassdoor est.),description the senior data scientist is resp...,3.1,healthfirst,"new york, new york","new york, new york",1001 to 5000 employees,1993,nonprofit organization,insurance carriers,insurance,unknown / non-applicable,"emblemhealth, unitedhealth group, aetna",per year,1,0.000000,False
1,1,data scientist,137000-171000 (glassdoor est.),"secure our nation, ignite your future join th...",4.2,mantech,"chantilly, virginia","herndon, virginia",5001 to 10000 employees,1968,company - public,research & development,business services,$1 to $2 billion (usd),-1,per year,2,5.884063,False
2,2,data scientist,137000-171000 (glassdoor est.),overview analysis group is one of the larges...,3.8,analysis group,"boston, massachusetts","boston, massachusetts",1001 to 5000 employees,1981,private practice / firm,consulting,business services,$100 to $500 million (usd),-1,per year,3,0.000000,False
3,3,data scientist,137000-171000 (glassdoor est.),job description: do you have a passion for da...,3.5,inficon,"newton, massachusetts","bad ragaz, switzerland",501 to 1000 employees,2000,company - public,electrical & electronic manufacturing,manufacturing,$100 to $500 million (usd),"mks instruments, pfeiffer vacuum, agilent tech...",per year,4,3798.189362,True
4,4,data scientist,137000-171000 (glassdoor est.),data scientist affinity solutions / marketing ...,2.9,affinity solutions,"new york, new york","new york, new york",51 to 200 employees,1998,company - private,advertising & marketing,business services,unknown / non-applicable,"commerce signals, cardlytics, yodlee",per year,5,0.000000,False

In [17]:
df["Remote"] = df["Remote"].apply(lambda x: "yes" if x else "no")
df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Salary Type,Company ID,Distance,Remote
0,0,sr data scientist,137000-171000 (glassdoor est.),description the senior data scientist is resp...,3.1,healthfirst,"new york, new york","new york, new york",1001 to 5000 employees,1993,nonprofit organization,insurance carriers,insurance,unknown / non-applicable,"emblemhealth, unitedhealth group, aetna",per year,1,0.000000,no
1,1,data scientist,137000-171000 (glassdoor est.),"secure our nation, ignite your future join th...",4.2,mantech,"chantilly, virginia","herndon, virginia",5001 to 10000 employees,1968,company - public,research & development,business services,$1 to $2 billion (usd),-1,per year,2,5.884063,no
2,2,data scientist,137000-171000 (glassdoor est.),overview analysis group is one of the larges...,3.8,analysis group,"boston, massachusetts","boston, massachusetts",1001 to 5000 employees,1981,private practice / firm,consulting,business services,$100 to $500 million (usd),-1,per year,3,0.000000,no
3,3,data scientist,137000-171000 (glassdoor est.),job description: do you have a passion for da...,3.5,inficon,"newton, massachusetts","bad ragaz, switzerland",501 to 1000 employees,2000,company - public,electrical & electronic manufacturing,manufacturing,$100 to $500 million (usd),"mks instruments, pfeiffer vacuum, agilent tech...",per year,4,3798.189362,yes
4,4,data scientist,137000-171000 (glassdoor est.),data scientist affinity solutions / marketing ...,2.9,affinity solutions,"new york, new york","new york, new york",51 to 200 employees,1998,company - private,advertising & marketing,business services,unknown / non-applicable,"commerce signals, cardlytics, yodlee",per year,5,0.000000,no

In [218]:
df["Revenue"] = df["Revenue"].str.replace("unknown / non-applicable", "", regex=True)

In [19]:
df.head(632)

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Salary Type,Company ID,Distance,Remote
0,0,sr data scientist,137000-171000 (glassdoor est.),description the senior data scientist is resp...,3.1,healthfirst,"new york, new york","new york, new york",1001 to 5000 employees,1993,nonprofit organization,insurance carriers,insurance,,"emblemhealth, unitedhealth group, aetna",per year,1,0.000000,no
1,1,data scientist,137000-171000 (glassdoor est.),"secure our nation, ignite your future join th...",4.2,mantech,"chantilly, virginia","herndon, virginia",5001 to 10000 employees,1968,company - public,research & development,business services,$1 to $2 billion (usd),-1,per year,2,5.884063,no
2,2,data scientist,137000-171000 (glassdoor est.),overview analysis group is one of the larges...,3.8,analysis group,"boston, massachusetts","boston, massachusetts",1001 to 5000 employees,1981,private practice / firm,consulting,business services,$100 to $500 million (usd),-1,per year,3,0.000000,no
3,3,data scientist,137000-171000 (glassdoor est.),job description: do you have a passion for da...,3.5,inficon,"newton, massachusetts","bad ragaz, switzerland",501 to 1000 employees,2000,company - public,electrical & electronic manufacturing,manufacturing,$100 to $500 million (usd),"mks instruments, pfeiffer vacuum, agilent tech...",per year,4,3798.189362,yes
4,4,data scientist,137000-171000 (glassdoor est.),data scientist affinity solutions / marketing ...,2.9,affinity solutions,"new york, new york","new york, new york",51 to 200 employees,1998,company - private,advertising & marketing,business services,,"commerce signals, cardlytics, yodlee",per year,5,0.000000,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
627,627,data scientist,87000-141000 (glassdoor est.),job description data scientist location: the ...,4.6,murray resources,"the woodlands, texas","houston, texas",1 to 50 employees,1988,company - private,staffing & outsourcing,business services,$10 to $25 million (usd),-1,per year,348,29.908964,no
628,628,data scientist,87000-141000 (glassdoor est.),"geotab, a global leader in iot and connected t...",4.3,geotab,"oakville, california","oakville, canada",1001 to 5000 employees,2000,company - private,computer hardware & software,information technology,$100 to $500 million (usd),-1,per year,415,2231.072919,yes
629,629,data scientist,87000-141000 (glassdoor est.),job description data scientist duration: 6+ mo...,4.7,crs group,"chicago, illinois","itasca, illinois",51 to 200 employees,1994,company - private,staffing & outsourcing,business services,$10 to $25 million (usd),-1,per year,352,20.571130,no
630,630,data scientist,87000-141000 (glassdoor est.),"eglobaltech, one of northern virginia’s fastes...",3.7,eglobaltech,"arlington, virginia","vienna, virginia",201 to 500 employees,2004,company - private,it services,information technology,,-1,per year,416,9.615353,no
631,631,"data scientist, kinship - nyc/portland",92000-155000 (glassdoor est.),back to search results previous job next job ...,3.9,mars,"new york, new york","mc lean, virginia",10000+ employees,1911,company - private,food & beverage manufacturing,manufacturing,$10+ billion (usd),-1,per year,83,208.448633,yes

In [219]:
import re

def handle_specific_revenue_formats(revenue_str):
   
    pattern_mixed_range = r'\$(\d+([.,]\d+)?)\s*(million|billion)?\s*(to|-)\s*\$?(\d+([.,]\d+)?)?\s*(million|billion)?'
    match_mixed_range = re.search(pattern_mixed_range, str(revenue_str), re.IGNORECASE)

    if match_mixed_range:
        min_revenue = float(match_mixed_range.group(1).replace(',', ''))
        min_unit = match_mixed_range.group(3)
        max_revenue = float(match_mixed_range.group(5).replace(',', '')) if match_mixed_range.group(5) else min_revenue
        max_unit = match_mixed_range.group(7)

        
        if min_unit and min_unit.lower() == 'billion':
            min_revenue *= 1000
        if max_unit and max_unit.lower() == 'billion':
            max_revenue *= 1000

        return min_revenue, max_revenue

    
    pattern_plus_billion = r'\$(\d+)\+\s*billion'
    match_plus_billion = re.search(pattern_plus_billion, str(revenue_str), re.IGNORECASE)

    if match_plus_billion:
        min_revenue = float(match_plus_billion.group(1)) * 1000  
        return min_revenue, min_revenue  

    
    pattern_less_than_million = r'less than \$1 million'
    match_less_than_million = re.search(pattern_less_than_million, str(revenue_str), re.IGNORECASE)

    if match_less_than_million:
        return 0, 1  

  
    return float('nan'), float('nan')

df[['MinRevenue', 'MaxRevenue']] = df['Revenue'].apply(lambda x: pd.Series(handle_specific_revenue_formats(x)))

In [247]:
df['MaxRevenue']=df['MaxRevenue'].astype(str)
df['MinRevenue']=df['MinRevenue'].astype(str)
df['MinRevenue'].dtype

dtype('O')

In [250]:
import re

df["MinRevenue"] = df.apply(lambda x: re.sub(r"\.0$", "b", x["MinRevenue"]) if "billion" in x['Revenue'] else x['MinRevenue'], axis=1)
df["MaxRevenue"] = df.apply(lambda x: re.sub(r"\.0$", "b", x["MaxRevenue"]) if "billion" in x['Revenue'] else x['MaxRevenue'], axis=1)
df["MinRevenue"] = df.apply(lambda x: re.sub(r"\.0$", "m", x["MinRevenue"]) if "million" in x['Revenue'] else x['MinRevenue'], axis=1)
df["MaxRevenue"] = df.apply(lambda x: re.sub(r"\.0$", "m", x["MaxRevenue"]) if "million" in x['Revenue'] else x['MaxRevenue'], axis=1)
df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,MinRevenue,MaxRevenue,Job Description Length (Words),Job Description Length (Characters),Experience Level,Size Category,Salary Outlier,Rating Outlier,Founded Year Outlier,Average Salary
0,0,sr data scientist,137000-171000 (glassdoor est.),description the senior data scientist is resp...,3.1,healthfirst,"new york, new york","new york, new york",1001 to 5000 employees,1993,...,nan,nan,469,3389,senior level,medium,False,False,False,154000.0
1,1,data scientist,137000-171000 (glassdoor est.),"secure our nation, ignite your future join th...",4.2,mantech,"chantilly, virginia","herndon, virginia",5001 to 10000 employees,1968,...,1b,2000b,542,4076,mid level,large,False,False,False,154000.0
2,2,data scientist,137000-171000 (glassdoor est.),overview analysis group is one of the larges...,3.8,analysis group,"boston, massachusetts","boston, massachusetts",1001 to 5000 employees,1981,...,100m,500m,1262,8749,senior level,medium,False,False,False,154000.0
3,3,data scientist,137000-171000 (glassdoor est.),job description: do you have a passion for da...,3.5,inficon,"newton, massachusetts","bad ragaz, switzerland",501 to 1000 employees,2000,...,100m,500m,452,3349,Unknown,small,False,False,False,154000.0
4,4,data scientist,137000-171000 (glassdoor est.),data scientist affinity solutions / marketing ...,2.9,affinity solutions,"new york, new york","new york, new york",51 to 200 employees,1998,...,nan,nan,378,2728,senior level,small,False,False,False,154000.0

6. Missing Data Handling:
• Fill Missing Values in Categorical Columns: Fill missing values
in columns such as ”Industry” and ”Sector.”
• Fill Missing Values in Rating: Fill missing values in ”Rating.”
7. Cleaning and Extracting Data from ”Job Description”:
• Length Calculation: Create a column to calculate the word count
or character length of each ”Job Description” to help filter lengthy
descriptions.
• Remote Work Flag: Identify if the job allows remote work by
checking for keywords (like ”remote,” ”telecommute”) in the ”Job
Description”.

• Experience Level Parsing: Add columns to identify required ex-
perience levels (e.g., ”entry level,” ”5+ years”) by parsing ”Job De-
scription.”

8. Additional Column Standardization:
• Numeric Conversion of Founding Year: Ensure ”Founded” is a
numeric column, and set a minimum year threshold (e.g., 1800) to
filter out any erroneous entries.
• Size Categorization: For ”Size,” create size categories (e.g.,
”small,” ”medium,” ”large”) based on ranges in employee count.
9. Outlier Detection and Handling:

• Salary Outliers: Detect outliers in the salary range and flag unusu-
ally high or low salary estimates for each job title.

• Rating Outliers: Identify extreme ratings (e.g., below 2.0 or above
4.5) and flag them to verify their accuracy.

• Founded Year Outliers: Flag companies with founding years out-
side a realistic range as potential data entry errors.

10. Column Optimization and Data Type Conversion:
• Convert Numerical Columns: Ensure columns like ”Rating” and
”Founded” are in a suitable numeric format (int64 or float64) and
convert others as appropriate.

• Memory Optimization: Downcast numeric columns (e.g., ”Rat-
ing,” ”Founded”) to the smallest integer or float type without data

loss to optimize memory usage.

In [220]:
import numpy as np 

df['Revenue'].fillna(value=np.nan, inplace=True) 
df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Salary Type,Company ID,MinRevenue,MaxRevenue
0,0,sr data scientist,137000-171000 (glassdoor est.),description the senior data scientist is resp...,3.1,healthfirst,"new york, new york","new york, new york",1001 to 5000 employees,1993,nonprofit organization,insurance carriers,insurance,,"emblemhealth, unitedhealth group, aetna",per year,1,NaN,NaN
1,1,data scientist,137000-171000 (glassdoor est.),"secure our nation, ignite your future join th...",4.2,mantech,"chantilly, virginia","herndon, virginia",5001 to 10000 employees,1968,company - public,research & development,business services,$1 to $2 billion (usd),-1,per year,2,1.0,2000.0
2,2,data scientist,137000-171000 (glassdoor est.),overview analysis group is one of the larges...,3.8,analysis group,"boston, massachusetts","boston, massachusetts",1001 to 5000 employees,1981,private practice / firm,consulting,business services,$100 to $500 million (usd),-1,per year,3,100.0,500.0
3,3,data scientist,137000-171000 (glassdoor est.),job description: do you have a passion for da...,3.5,inficon,"newton, massachusetts","bad ragaz, switzerland",501 to 1000 employees,2000,company - public,electrical & electronic manufacturing,manufacturing,$100 to $500 million (usd),"mks instruments, pfeiffer vacuum, agilent tech...",per year,4,100.0,500.0
4,4,data scientist,137000-171000 (glassdoor est.),data scientist affinity solutions / marketing ...,2.9,affinity solutions,"new york, new york","new york, new york",51 to 200 employees,1998,company - private,advertising & marketing,business services,,"commerce signals, cardlytics, yodlee",per year,5,NaN,NaN

In [24]:

df.head(632)

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,Industry,Sector,Revenue,Competitors,Salary Type,Company ID,Distance,Remote,MinRevenue,MaxRevenue
0,0,sr data scientist,137000-171000 (glassdoor est.),description the senior data scientist is resp...,3.1,healthfirst,"new york, new york","new york, new york",1001 to 5000 employees,1993,...,insurance carriers,insurance,,"emblemhealth, unitedhealth group, aetna",per year,1,0.000000,no,nan,nan
1,1,data scientist,137000-171000 (glassdoor est.),"secure our nation, ignite your future join th...",4.2,mantech,"chantilly, virginia","herndon, virginia",5001 to 10000 employees,1968,...,research & development,business services,$1 to $2 billion (usd),-1,per year,2,5.884063,no,1m,2000m
2,2,data scientist,137000-171000 (glassdoor est.),overview analysis group is one of the larges...,3.8,analysis group,"boston, massachusetts","boston, massachusetts",1001 to 5000 employees,1981,...,consulting,business services,$100 to $500 million (usd),-1,per year,3,0.000000,no,100m,500m
3,3,data scientist,137000-171000 (glassdoor est.),job description: do you have a passion for da...,3.5,inficon,"newton, massachusetts","bad ragaz, switzerland",501 to 1000 employees,2000,...,electrical & electronic manufacturing,manufacturing,$100 to $500 million (usd),"mks instruments, pfeiffer vacuum, agilent tech...",per year,4,3798.189362,yes,100m,500m
4,4,data scientist,137000-171000 (glassdoor est.),data scientist affinity solutions / marketing ...,2.9,affinity solutions,"new york, new york","new york, new york",51 to 200 employees,1998,...,advertising & marketing,business services,,"commerce signals, cardlytics, yodlee",per year,5,0.000000,no,nan,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
627,627,data scientist,87000-141000 (glassdoor est.),job description data scientist location: the ...,4.6,murray resources,"the woodlands, texas","houston, texas",1 to 50 employees,1988,...,staffing & outsourcing,business services,$10 to $25 million (usd),-1,per year,348,29.908964,no,10m,25m
628,628,data scientist,87000-141000 (glassdoor est.),"geotab, a global leader in iot and connected t...",4.3,geotab,"oakville, california","oakville, canada",1001 to 5000 employees,2000,...,computer hardware & software,information technology,$100 to $500 million (usd),-1,per year,415,2231.072919,yes,100m,500m
629,629,data scientist,87000-141000 (glassdoor est.),job description data scientist duration: 6+ mo...,4.7,crs group,"chicago, illinois","itasca, illinois",51 to 200 employees,1994,...,staffing & outsourcing,business services,$10 to $25 million (usd),-1,per year,352,20.571130,no,10m,25m
630,630,data scientist,87000-141000 (glassdoor est.),"eglobaltech, one of northern virginia’s fastes...",3.7,eglobaltech,"arlington, virginia","vienna, virginia",201 to 500 employees,2004,...,it services,information technology,,-1,per year,416,9.615353,no,nan,nan
631,631,"data scientist, kinship - nyc/portland",92000-155000 (glassdoor est.),back to search results previous job next job ...,3.9,mars,"new york, new york","mc lean, virginia",10000+ employees,1911,...,food & beverage manufacturing,manufacturing,$10+ billion (usd),-1,per year,83,208.448633,yes,10000m,10000m

In [221]:
#6
empty_values = df[df["Rating"] == ""]

numeric_values = df[pd.to_numeric(df["Rating"], errors='coerce').notnull()]

unknown_values = df[df["Rating"].isnull()]

all_problematic_values = pd.concat([empty_values, numeric_values, unknown_values])
print(all_problematic_values["Rating"].unique())

[ 3.1  4.2  3.8  3.5  2.9  3.9  4.4  3.6  4.5  4.7  3.7  3.4  4.1  3.2
  4.3  2.8  5.   4.8  3.3  2.7  2.2  2.6  4.   2.5  4.9  2.4 -1.   2.3
  4.6  3.   2.1  2. ]

In [222]:
df['Sector'] = df['Sector'].fillna('nan')
df['Industry'] = df['Industry'].fillna('nan')
df['Rating'] = df['Rating'].fillna('nan')

In [223]:
df["Rating"] = df["Rating"].apply(lambda x: str(x).replace(".","",1) if str(x).endswith(".") and str(x)[:-1].isdigit() else x)

In [224]:

df["Rating"] = df["Rating"].apply(lambda x: str(x).replace("-","",1) if str(x).startswith(".") and str(x)[:-1].isdigit() else x)

In [225]:
#7
df['Job Description Length (Words)'] = df['Job Description'].apply(lambda x: len(str(x).split()))
df['Job Description Length (Characters)'] = df['Job Description'].apply(lambda x: len(str(x)))

In [30]:
df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,Revenue,Competitors,Salary Type,Company ID,Distance,Remote,MinRevenue,MaxRevenue,Job Description Length (Words),Job Description Length (Characters)
0,0,sr data scientist,137000-171000 (glassdoor est.),description the senior data scientist is resp...,3.1,healthfirst,"new york, new york","new york, new york",1001 to 5000 employees,1993,...,,"emblemhealth, unitedhealth group, aetna",per year,1,0.000000,no,nan,nan,469,3389
1,1,data scientist,137000-171000 (glassdoor est.),"secure our nation, ignite your future join th...",4.2,mantech,"chantilly, virginia","herndon, virginia",5001 to 10000 employees,1968,...,$1 to $2 billion (usd),-1,per year,2,5.884063,no,1m,2000m,542,4076
2,2,data scientist,137000-171000 (glassdoor est.),overview analysis group is one of the larges...,3.8,analysis group,"boston, massachusetts","boston, massachusetts",1001 to 5000 employees,1981,...,$100 to $500 million (usd),-1,per year,3,0.000000,no,100m,500m,1262,8749
3,3,data scientist,137000-171000 (glassdoor est.),job description: do you have a passion for da...,3.5,inficon,"newton, massachusetts","bad ragaz, switzerland",501 to 1000 employees,2000,...,$100 to $500 million (usd),"mks instruments, pfeiffer vacuum, agilent tech...",per year,4,3798.189362,yes,100m,500m,452,3349
4,4,data scientist,137000-171000 (glassdoor est.),data scientist affinity solutions / marketing ...,2.9,affinity solutions,"new york, new york","new york, new york",51 to 200 employees,1998,...,,"commerce signals, cardlytics, yodlee",per year,5,0.000000,no,nan,nan,378,2728

In [226]:
filtered_words = df[df['Job Description Length (Words)'] < 500]
filtered_words

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,Industry,Sector,Revenue,Competitors,Salary Type,Company ID,MinRevenue,MaxRevenue,Job Description Length (Words),Job Description Length (Characters)
0,0,sr data scientist,137000-171000 (glassdoor est.),description the senior data scientist is resp...,3.1,healthfirst,"new york, new york","new york, new york",1001 to 5000 employees,1993,...,insurance carriers,insurance,,"emblemhealth, unitedhealth group, aetna",per year,1,NaN,NaN,469,3389
3,3,data scientist,137000-171000 (glassdoor est.),job description: do you have a passion for da...,3.5,inficon,"newton, massachusetts","bad ragaz, switzerland",501 to 1000 employees,2000,...,electrical & electronic manufacturing,manufacturing,$100 to $500 million (usd),"mks instruments, pfeiffer vacuum, agilent tech...",per year,4,100.0,500.0,452,3349
4,4,data scientist,137000-171000 (glassdoor est.),data scientist affinity solutions / marketing ...,2.9,affinity solutions,"new york, new york","new york, new york",51 to 200 employees,1998,...,advertising & marketing,business services,,"commerce signals, cardlytics, yodlee",per year,5,NaN,NaN,378,2728
7,7,data scientist,137000-171000 (glassdoor est.),introduction have you always wanted to run ex...,3.5,irobot,"bedford, massachusetts","bedford, massachusetts",1001 to 5000 employees,1990,...,consumer electronics & appliances stores,retail,$1 to $2 billion (usd),-1,per year,8,1.0,2000.0,250,1736
8,8,staff data scientist - analytics,137000-171000 (glassdoor est.),intuit is seeking a staff data scientist to co...,4.4,intuit - data,"san diego, california","mountain view, california",5001 to 10000 employees,1983,...,computer hardware & software,information technology,$2 to $5 billion (usd),"square, paypal, h&r block",per year,9,2.0,5000.0,68,456
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
665,665,data scientist,105000-167000 (glassdoor est.),criterion systems seeks a data scientist to su...,3.8,"criterion systems, inc.","vienna, virginia","vienna, virginia",201 to 500 employees,2005,...,it services,information technology,$50 to $100 million (usd),-1,per year,430,50.0,100.0,344,2667
668,668,data scientist,105000-167000 (glassdoor est.),job description become a thought leader within...,-1.0,jkgt,"san francisco, california",-1,-1,-1,...,-1,-1,-1,-1,per year,433,NaN,NaN,162,1251
669,669,data scientist,105000-167000 (glassdoor est.),join a thriving company that is changing the w...,-1.0,accesshope,"irwindale, california",-1,-1,-1,...,-1,-1,-1,-1,per year,434,NaN,NaN,393,2793
670,670,data scientist,105000-167000 (glassdoor est.),100 remote opportunity as an ainlp data scient...,5.0,chateck incorporated,"san francisco, california","santa clara, california",1 to 50 employees,-1,...,advertising & marketing,business services,$1 to $5 million (usd),-1,per year,435,1.0,5.0,455,3426
671,671,data scientist,105000-167000 (glassdoor est.),description the data scientist will be part o...,2.7,1-800-flowers,"new york, new york","carle place, new york",1001 to 5000 employees,1976,...,wholesale,business services,$1 to $2 billion (usd),-1,per year,365,1.0,2000.0,421,3000

In [227]:
remote_work = df.apply(lambda x: x["Company ID"] if "remote" in x["Job Description"] else None, axis=1)
remote_work.dropna(inplace=True)
remote_work

14      15.0
17      18.0
34      33.0
53      52.0
70      67.0
       ...
654    359.0
655    361.0
667    432.0
670    435.0
671    365.0
Length: 63, dtype: float64

In [228]:
import re

df["Experience Level"] = df["Job Description"].apply(lambda x: \
    "entry level" if re.search(r"(entry\s?level|junior|graduate)", x, re.IGNORECASE) else \
    "mid level" if re.search(r"(mid\s?level|intermediate|3-5\s?years|3\+? years|4-6\s?years|4\+? years|5-7\s?years|5\+? years)", x, re.IGNORECASE) else \
    "senior level" if re.search(r"(senior|lead|principal|manager|director|executive|7\+? years|8\+? years|9\+? years|10\+? years)", x, re.IGNORECASE) else \
    "Unknown")

In [229]:
#8
df["Founded"] = pd.to_numeric(df["Founded"], errors='coerce') 
df["Founded"] = df["Founded"].apply(lambda x: x if x >= 1800 else np.nan)

In [230]:
import numpy as np

def categorize_size(size_str):
  
    try:
        
        size_num = int(''.join(filter(str.isdigit, size_str.split()[0])))  
        if size_num <= 1000:
            return "small"
        elif 1001 <= size_num <= 5000:
            return "medium"
        elif size_num > 5000:
            return "large"
    except ValueError:
        return np.nan  

df['Size Category'] = df['Size'].apply(categorize_size)

In [ ]:
df.head()

In [231]:
#9
def is_salary_outlier(row):
    
    job_title = row['Job Title']
    
    
    try:
        salary = pd.to_numeric(row['Salary Estimate'])
    except ValueError:
        return False  

    job_data = df[df['Job Title'] == job_title]['Salary Estimate']
    
    job_data = pd.to_numeric(job_data, errors='coerce')
    
    
    mean_salary = job_data.mean()
    std_salary = job_data.std()
    threshold = 2

    return abs(salary - mean_salary) > threshold * std_salary

df['Salary Outlier'] = df.apply(is_salary_outlier, axis=1)

df['Rating Outlier'] = df['Rating'].apply(lambda rating: (rating < 2.0) or (rating > 4.5))

current_year = 2024
df['Founded Year Outlier'] = df['Founded'].apply(lambda year: (year < 1800) or (year > current_year))

In [232]:
#10
df['Rating'] = pd.to_numeric(df['Rating'], errors='coerce').astype('float64')
df['Founded'] = pd.to_numeric(df['Founded'], errors='coerce').astype('Int64')
df['MinRevenue']=pd.to_numeric(df['MinRevenue'], errors='coerce').astype(pd.Int64Dtype())
df['MaxRevenue']=pd.to_numeric(df['MaxRevenue'], errors='coerce').astype(pd.Int64Dtype())

In [255]:
df['Rating'] = pd.to_numeric(df['Rating'], errors='coerce').astype(pd.Float32Dtype()) 
df['Founded'] = pd.to_numeric(df['Founded'], errors='coerce').astype(pd.Int32Dtype()) 
df['index'] = pd.to_numeric(df['index'], errors='coerce').astype(pd.Int32Dtype())
df['Company ID'] = pd.to_numeric(df['Company ID'], errors='coerce').astype(pd.Int32Dtype())
df['Job Description Length (Words)'] = pd.to_numeric(df['Job Description Length (Words)'], errors='coerce').astype(pd.Int32Dtype())
df['Job Description Length (Characters)'] = pd.to_numeric(df['Job Description Length (Characters)'], errors='coerce').astype(pd.Int32Dtype())
df['MinRevenue']=pd.to_numeric(df['MinRevenue'], errors='coerce').astype(pd.Int32Dtype())
df['MaxRevenue']=pd.to_numeric(df['MaxRevenue'], errors='coerce').astype(pd.Int32Dtype())
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 672 entries, 0 to 671
Data columns (total 27 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   index                                672 non-null    Int32
 1   Job Title                            672 non-null    object
 2   Salary Estimate                      672 non-null    object
 3   Job Description                      672 non-null    object
 4   Rating                               672 non-null    Float32
 5   Company Name                         672 non-null    object
 6   Location                             672 non-null    object
 7   Headquarters                         672 non-null    object
 8   Size                                 672 non-null    object
 9   Founded                              551 non-null    Int32
 10  Type of ownership                    672 non-null    object
 11  Industry                             672 non-null    object
 12  Sector                               672 non-null    object
 13  Revenue                              672 non-null    object
 14  Competitors                          672 non-null    object
 15  Salary Type                          672 non-null    object
 16  Company ID                           672 non-null    Int32
 17  MinRevenue                           432 non-null    Int32
 18  MaxRevenue                           432 non-null    Int32
 19  Job Description Length (Words)       672 non-null    Int32
 20  Job Description Length (Characters)  672 non-null    Int32
 21  Experience Level                     672 non-null    object
 22  Size Category                        655 non-null    object
 23  Salary Outlier                       672 non-null    bool
 24  Rating Outlier                       672 non-null    bool
 25  Founded Year Outlier                 672 non-null    bool
 26  Average Salary                       652 non-null    float64
dtypes: Float32(1), Int32(7), bool(3), float64(1), object(15)
memory usage: 112.3+ KB

Exploratory Data Analysis (EDA)

In [234]:
#1

def extract_salary_range(salary_estimate):
    try:
        salary_range = salary_estimate.split('-') 
        min_salary = int(salary_range[0]) 
        max_salary = int(salary_range[1].split(" ")[0])
        return (min_salary + max_salary) / 2 
    except (AttributeError, ValueError, IndexError):
        return np.nan  
df['Average Salary'] = df['Salary Estimate'].apply(extract_salary_range)


salary_stats = df.groupby(['Job Title', 'Industry', 'Sector'])['Average Salary'].agg(['median', 'mean', 'std'])

print(salary_stats)

                                                                                                                        median  \
Job Title                                          Industry                                Sector
(sr.) data scientist -                             banks & credit unions                   finance                    109500.0
ai data scientist                                  federal agencies                        government                  99500.0
ai ops data scientist                              biotech & pharmaceuticals               biotech & pharmaceuticals  114000.0
ai/ml - machine learning scientist, siri unders... computer hardware & software            information technology     123500.0
analytics - business assurance data analyst        lending                                 finance                    118750.0
...                                                                                                                        ...
statistical scientist                              biotech & pharmaceuticals               biotech & pharmaceuticals   76500.0
tableau data engineer 20-0117                      enterprise software & network solutions information technology      99500.0
vice president, biometrics and clinical data ma... biotech & pharmaceuticals               biotech & pharmaceuticals  148000.0
vp, data science                                   research & development                  business services           78250.0
weapons and sensors engineer/scientist             aerospace & defense                     aerospace & defense        142250.0

                                                                                                                          mean  \
Job Title                                          Industry                                Sector
(sr.) data scientist -                             banks & credit unions                   finance                    109500.0
ai data scientist                                  federal agencies                        government                  99500.0
ai ops data scientist                              biotech & pharmaceuticals               biotech & pharmaceuticals  110000.0
ai/ml - machine learning scientist, siri unders... computer hardware & software            information technology     123500.0
analytics - business assurance data analyst        lending                                 finance                    118750.0
...                                                                                                                        ...
statistical scientist                              biotech & pharmaceuticals               biotech & pharmaceuticals   76500.0
tableau data engineer 20-0117                      enterprise software & network solutions information technology      99500.0
vice president, biometrics and clinical data ma... biotech & pharmaceuticals               biotech & pharmaceuticals  148000.0
vp, data science                                   research & development                  business services           78250.0
weapons and sensors engineer/scientist             aerospace & defense                     aerospace & defense        142250.0

                                                                                                                               std
Job Title                                          Industry                                Sector
(sr.) data scientist -                             banks & credit unions                   finance                     6363.961031
ai data scientist                                  federal agencies                        government                          NaN
ai ops data scientist                              biotech & pharmaceuticals               biotech & pharmaceuticals  15882.380174
ai/ml - machine learning scientist, siri unders... computer hardware & software            information technology              NaN
analytics - business assurance data analyst        lending                                 finance                    59750.523010
...                                                                                                                            ...
statistical scientist                              biotech & pharmaceuticals               biotech & pharmaceuticals           NaN
tableau data engineer 20-0117                      enterprise software & network solutions information technology              NaN
vice president, biometrics and clinical data ma... biotech & pharmaceuticals               biotech & pharmaceuticals           NaN
vp, data science                                   research & development                  business services          49143.921292
weapons and sensors engineer/scientist             aerospace & defense                     aerospace & defense         8131.727984

[269 rows x 3 columns]

In [235]:
mean_sal =df.groupby('Company Name')['Average Salary'].mean()
sort = mean_sal.sort_values(ascending=False)
sort.dropna(inplace=True)
highest_average_companies = sort.head(6)
Lowest_average_companies = sort.tail(6)

Lowest_average_companies

Company Name
fleetcor                  43500.0
radiant digital           43500.0
trexquant investment      43500.0
intellipro group inc.     43500.0
apex systems              43500.0
linquest                  43500.0
Name: Average Salary, dtype: float64

In [236]:
rating_category = df['Rating'].apply(lambda x: '< 3.0' if x < 3.0 else ('3.0 - 4.0' if 3.0 <= x <= 4.0 else '> 4.0'))
total_companies = len(df)
rating_proportions = {
    category: rating_category.apply(lambda x: x == category).sum() / total_companies
    for category in ['< 3.0', '3.0 - 4.0', '> 4.0']
}

print("Proportion of Companies in Rating Ranges:")
for label, proportion in rating_proportions.items():
    print(f"{label}: {proportion:.2%}")

Proportion of Companies in Rating Ranges:
< 3.0: 13.10%
3.0 - 4.0: 53.42%
> 4.0: 33.48%

In [237]:
#2
industry_counts = df.groupby('Sector')['Industry'].nunique()
total_unique_industries = df['Industry'].nunique()
industry_proportions = industry_counts / total_unique_industries
print("Number of Unique Industries within Each Sector:")
print(industry_counts)
print("\nProportion of Industries within Each Sector:")
print(industry_proportions)

Number of Unique Industries within Each Sector:
Sector
-1                                    1
accounting & legal                    1
aerospace & defense                   1
agriculture & forestry                2
biotech & pharmaceuticals             1
business services                     6
construction, repair & maintenance    1
consumer services                     1
education                             1
finance                               5
government                            2
health care                           1
information technology                4
insurance                             2
manufacturing                         7
media                                 3
non-profit                            1
oil, gas, energy & utilities          3
real estate                           1
retail                                4
telecommunications                    3
transportation & logistics            5
travel & tourism                      2
Name: Industry, dtype: int64

Proportion of Industries within Each Sector:
Sector
-1                                    0.017241
accounting & legal                    0.017241
aerospace & defense                   0.017241
agriculture & forestry                0.034483
biotech & pharmaceuticals             0.017241
business services                     0.103448
construction, repair & maintenance    0.017241
consumer services                     0.017241
education                             0.017241
finance                               0.086207
government                            0.034483
health care                           0.017241
information technology                0.068966
insurance                             0.034483
manufacturing                         0.120690
media                                 0.051724
non-profit                            0.017241
oil, gas, energy & utilities          0.051724
real estate                           0.017241
retail                                0.068966
telecommunications                    0.051724
transportation & logistics            0.086207
travel & tourism                      0.034483
Name: Industry, dtype: float64

In [238]:
df['Industry']=df['Industry'].replace(' ',np.nan)
df['Industry']=df['Industry'].dropna()
data_science_df = df[df['Job Title'].str.contains('data scientist', na=False)]

industry_stats = data_science_df.groupby('Industry').agg(
    {'Job Title': 'count', 'Average Salary': 'mean', 'Rating': 'mean'}
)

industry_stats = industry_stats.rename(
    columns={
        'Job Title': 'Job Count',
        'Average Salary': 'Avg Salary',
        'Rating': 'Avg Rating',
        })
    
top_5_industries = industry_stats.sort_values('Job Count', ascending=False).head(6)

print(top_5_industries)

                              Job Count     Avg Salary  Avg Rating
Industry
-1                                   64  125245.901639    1.054688
it services                          50  112053.191489       3.688
staffing & outsourcing               35  127323.529412    4.137143
biotech & pharmaceuticals            33  122984.848485    3.712121
computer hardware & software         33  120734.375000    4.224242
aerospace & defense                  31  138000.000000    3.558065

In [251]:

df["MinRevenue"]=df["MinRevenue"].replace('m','000000',regex=True).replace('b','000000000',regex=True)
df["MaxRevenue"]=df["MaxRevenue"].replace('m','000000',regex=True).replace('b','000000000',regex=True)


df['MinRevenue'] = df['MinRevenue'].replace(r'\D+', '', regex=True)
df['MaxRevenue'] = df['MaxRevenue'].replace(r'\D+', '', regex=True)

In [252]:
df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,MinRevenue,MaxRevenue,Job Description Length (Words),Job Description Length (Characters),Experience Level,Size Category,Salary Outlier,Rating Outlier,Founded Year Outlier,Average Salary
0,0,sr data scientist,137000-171000 (glassdoor est.),description the senior data scientist is resp...,3.1,healthfirst,"new york, new york","new york, new york",1001 to 5000 employees,1993,...,,,469,3389,senior level,medium,False,False,False,154000.0
1,1,data scientist,137000-171000 (glassdoor est.),"secure our nation, ignite your future join th...",4.2,mantech,"chantilly, virginia","herndon, virginia",5001 to 10000 employees,1968,...,1000000000,2000000000000,542,4076,mid level,large,False,False,False,154000.0
2,2,data scientist,137000-171000 (glassdoor est.),overview analysis group is one of the larges...,3.8,analysis group,"boston, massachusetts","boston, massachusetts",1001 to 5000 employees,1981,...,100000000,500000000,1262,8749,senior level,medium,False,False,False,154000.0
3,3,data scientist,137000-171000 (glassdoor est.),job description: do you have a passion for da...,3.5,inficon,"newton, massachusetts","bad ragaz, switzerland",501 to 1000 employees,2000,...,100000000,500000000,452,3349,Unknown,small,False,False,False,154000.0
4,4,data scientist,137000-171000 (glassdoor est.),data scientist affinity solutions / marketing ...,2.9,affinity solutions,"new york, new york","new york, new york",51 to 200 employees,1998,...,,,378,2728,senior level,small,False,False,False,154000.0

In [160]:
data_science_df = df[df['Job Title'].str.contains('data scientist')]

In [182]:
df["Average Salary"]=pd.to_numeric(df["Average Salary"], errors='coerce').astype(pd.Int32Dtype())

industry_stats = data_science_df.groupby('Industry').agg(
    {'Job Title': 'count', 'Average Salary': 'mean', 'Rating': 'mean'}
)

top_5_industries = industry_stats.sort_values('Job Title', ascending=False).head(5)
top_5_industries['Average Salary'] = top_5_industries['Average Salary'].round(2)
top_5_industries['Rating'] = top_5_industries['Rating'].round(2)
print(top_5_industries)

                              Job Title  Average Salary  Rating
Industry
-1                                   64        125245.9    1.05
it services                          50       112053.19    3.69
staffing & outsourcing               35       127323.53    4.14
biotech & pharmaceuticals            33       122984.85    3.71
computer hardware & software         33       120734.38    4.22

In [181]:
df['Industry'] = df['Industry'].replace("0",np.nan)

In [192]:
df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,Salary Type,Company ID,Distance,Remote,MinRevenue,MaxRevenue,Job Description Length (Words),Job Description Length (Characters),Experience Level,Average Salary
0,0,sr data scientist,137000-171000 (glassdoor est.),description the senior data scientist is resp...,3.1,healthfirst,"new york, new york","new york, new york",1001 to 5000 employees,1993,...,per year,1,0.000000,no,,,469,3389,senior level,154000
1,1,data scientist,137000-171000 (glassdoor est.),"secure our nation, ignite your future join th...",4.2,mantech,"chantilly, virginia","herndon, virginia",5001 to 10000 employees,1968,...,per year,2,5.884063,no,1,2000,542,4076,mid level,154000
2,2,data scientist,137000-171000 (glassdoor est.),overview analysis group is one of the larges...,3.8,analysis group,"boston, massachusetts","boston, massachusetts",1001 to 5000 employees,1981,...,per year,3,0.000000,no,100,500,1262,8749,senior level,154000
3,3,data scientist,137000-171000 (glassdoor est.),job description: do you have a passion for da...,3.5,inficon,"newton, massachusetts","bad ragaz, switzerland",501 to 1000 employees,2000,...,per year,4,3798.189362,yes,100,500,452,3349,Unknown,154000
4,4,data scientist,137000-171000 (glassdoor est.),data scientist affinity solutions / marketing ...,2.9,affinity solutions,"new york, new york","new york, new york",51 to 200 employees,1998,...,per year,5,0.000000,no,,,378,2728,senior level,154000

In [262]:

df['MaxRevenue']=df['MaxRevenue'].fillna(0)
df['MaxRevenue']=df['MinRevenue'].fillna(0)


revenue_by_sector_industry = df.groupby(['Sector', 'Industry'])[['MinRevenue', 'MaxRevenue']].mean()

revenue_by_sector_industry = revenue_by_sector_industry.reset_index()

In [265]:

revenue_by_sector_industry['AverageRevenue'] = (revenue_by_sector_industry['MinRevenue'] + revenue_by_sector_industry['MaxRevenue']) / 2

In [266]:

most_profitable_areas = revenue_by_sector_industry.sort_values('AverageRevenue', ascending=False)

print(most_profitable_areas)

                                Sector  \
53          transportation & logistics
52          transportation & logistics
42        oil, gas, energy & utilities
29                       manufacturing
40        oil, gas, energy & utilities
50                  telecommunications
27                           insurance
55          transportation & logistics
32                       manufacturing
45                              retail
48                  telecommunications
21                          government
16                             finance
9                    business services
44                              retail
49                  telecommunications
4               agriculture & forestry
2                  aerospace & defense
33                       manufacturing
43                         real estate
28                           insurance
11                   business services
7                    business services
15                             finance
25              information technology
5            biotech & pharmaceuticals
38                               media
17                             finance
30                       manufacturing
23              information technology
35                       manufacturing
20                          government
31                       manufacturing
22                         health care
10                   business services
0                                   -1
26              information technology
8                    business services
46                              retail
34                       manufacturing
12  construction, repair & maintenance
18                             finance
47                              retail
24              information technology
19                             finance
41        oil, gas, energy & utilities
36                               media
39                          non-profit
6                    business services
13                   consumer services
1                   accounting & legal
37                               media
3               agriculture & forestry
14                           education
51          transportation & logistics
54          transportation & logistics
56                    travel & tourism
57                    travel & tourism

                                    Industry         MinRevenue  \
53                                      rail       2000000000.0
52                  logistics & supply chain       2000000000.0
42                                 utilities       2000000000.0
29                    chemical manufacturing  1522529109.333333
40                                    energy       1783793664.0
50               telecommunications services       1506250000.0
27           insurance agencies & brokerages       1354033728.0
55                 transportation management       1316134912.0
32             food & beverage manufacturing       1316134912.0
45       department, clothing, & shoe stores       1316134912.0
48     cable, internet & telephone providers       1316134912.0
21                 state & regional agencies       1316134912.0
16          financial transaction processing       1050000000.0
9                     research & development       1113852979.2
44  consumer electronics & appliances stores       1000000000.0
49          telecommunications manufacturing       1000000000.0
4                          timber operations       1000000000.0
2                        aerospace & defense  1054701337.263158
33                  industrial manufacturing        910756608.0
43                               real estate       1050000000.0
28                        insurance carriers   978418554.181818
11                                 wholesale       1000000000.0
7       architectural & engineering services        775378304.0
15                     banks & credit unions       1105378304.0
25                                  internet  1005206347.636364
5                  biotech & pharmaceuticals   791855930.434783
38                               video games       1000000000.0
17     investment banking & asset management        812500000.0
30           consumer products manufacturing        586453964.8
23              computer hardware & software   682419990.486486
35    transportation equipment manufacturing        705032704.0
20                          federal agencies   563636363.636364
31     electrical & electronic manufacturing   473711637.333333
22          health care services & hospitals   577570284.307692
10                    staffing & outsourcing   315454860.307692
0                                         -1   196233558.857143
26                               it services   139445605.463415
8                                 consulting        126867756.8
46                    food & beverage stores        100000000.0
34               miscellaneous manufacturing        100000000.0
12                              construction        100000000.0
18                                   lending    83333333.333333
47                       other retail stores        100000000.0
24   enterprise software & network solutions    77001421.913043
19          venture capital & private equity         50000000.0
41                        oil & gas services         50000000.0
36                               news outlet         50000000.0
39                         social assistance         25000000.0
6                    advertising & marketing         19187500.0
13                 health, beauty, & fitness          5000000.0
1                                 accounting                0.0
37                                publishing                0.0
3                      farm support services               <NA>
14                   colleges & universities               <NA>
51                 express delivery services               <NA>
54                                  shipping               <NA>
56                 hotels, motels, & resorts               <NA>
57                           travel agencies               <NA>

           MaxRevenue     AverageRevenue
53       2000000000.0       2000000000.0
52       2000000000.0       2000000000.0
42  1333333333.333333  1666666666.666667
29  1522529109.333333  1522529109.333333
40       1070276198.4       1427034931.2
50       1205000000.0       1355625000.0
27       1354033728.0       1354033728.0
55       1316134912.0       1316134912.0
32       1316134912.0       1316134912.0
45       1316134912.0       1316134912.0
48       1316134912.0       1316134912.0
21       1316134912.0       1316134912.0
16       1050000000.0       1050000000.0
9    982811452.235294  1048332215.717647
44       1000000000.0       1000000000.0
49       1000000000.0       1000000000.0
4        1000000000.0       1000000000.0
2     871275017.73913   962988177.501144
33        910756608.0        910756608.0
43        700000000.0        875000000.0
28   768757435.428571   873587994.805195
11   666666666.666667   833333333.333333
7         775378304.0        775378304.0
15        414516864.0        759947584.0
25        409528512.0   707367429.818182
5    551899587.878788   671877759.156785
38   333333333.333333   666666666.666667
17        500000000.0        656250000.0
30        586453964.8        586453964.8
23   442974379.789474    562697185.13798
35        352516352.0        528774528.0
20        387500000.0   475568181.818182
31   473711637.333333   473711637.333333
22   357543509.333333   467556896.820513
10   227828510.222222   271641685.264957
0     38693941.183099   117463750.020121
26    93725734.819672   116585670.141543
8    100158755.368421   113513256.084211
46        100000000.0        100000000.0
34        100000000.0        100000000.0
12        100000000.0        100000000.0
18         62500000.0    72916666.666667
47    33333333.333333    66666666.666667
24    41186807.069767    59094114.491405
19         50000000.0         50000000.0
41         50000000.0         50000000.0
36         50000000.0         50000000.0
39         25000000.0         25000000.0
6     13347826.086957    16267663.043478
13          5000000.0          5000000.0
1                 0.0                0.0
37                0.0                0.0
3                 0.0               <NA>
14                0.0               <NA>
51                0.0               <NA>
54                0.0               <NA>
56                0.0               <NA>
57                0.0               <NA>

In [268]:
#3

location_stats = df.groupby('Location').agg({'Job Title': 'count', 'Average Salary': 'mean', 'Rating': 'mean'})

location_stats = location_stats.rename(columns={'Job Title': 'Job Count', 'Average Salary': 'Avg Salary', 'Rating': 'Avg Rating'})

top_10_locations = location_stats.sort_values('Job Count', ascending=False).head(10)

print(top_10_locations)

                                  Job Count     Avg Salary  Avg Rating
Location
san francisco, california                69  118257.352941    2.476811
new york, new york                       50  132478.260870       3.592
washington, district of columbia         26  139500.000000    3.942308
boston, massachusetts                    24  122583.333333    4.004167
chicago, illinois                        22  118285.714286    3.668182
herndon, virginia                        21  134642.857143    3.933333
cambridge, massachusetts                 18  120666.666667         3.4
mclean, virginia                         12  120954.545455    4.008333
chantilly, virginia                      11  124181.818182    2.945455
united states                            11  113750.000000    3.209091

In [269]:

df['At Headquarters'] = df['Location'] == df['Headquarters']

hq_vs_remote_ratings = df.groupby('At Headquarters')['Rating'].mean()
print(hq_vs_remote_ratings)

At Headquarters
False    3.342432
True     3.782528
Name: Rating, dtype: Float32

In [270]:

location_size_correlation = df.groupby(['Location', 'Size Category'])['Job Title'].count().reset_index()

location_size_correlation = location_size_correlation.rename(columns={'Job Title': 'Job Count'})

location_size_pivot = location_size_correlation.pivot(index='Location', columns='Size Category', values='Job Count').fillna(0)

print(location_size_pivot)

Size Category           large  medium  small
Location
adelphi, maryland         2.0     0.0    0.0
akron, ohio               1.0     0.0    0.0
alexandria, virginia      2.0     0.0    2.0
alpharetta, georgia       0.0     1.0    1.0
ann arbor, michigan       0.0     2.0    0.0
...                       ...     ...    ...
winters, texas            0.0     0.0    1.0
woburn, massachusetts     0.0     0.0    3.0
woodbridge, new jersey    0.0     1.0    0.0
woodlawn, maryland        0.0     0.0    1.0
yakima, washington        0.0     0.0    1.0

[204 rows x 3 columns]

In [273]:
#4

job_level_stats = df.groupby('Experience Level').agg({'Rating': 'mean', 'Average Salary': 'mean'})
print(job_level_stats)

                    Rating  Average Salary
Experience Level
Unknown           3.716379   125433.035714
entry level       3.659091   122684.615385
mid level         3.366031   121139.763780
senior level      3.552632   120404.977376

In [274]:

experience_location_stats = df.groupby(['Location', 'Experience Level'])['Job Title'].count().reset_index()
experience_location_stats = experience_location_stats.rename(columns={'Job Title': 'Job Count'})

print(experience_location_stats)

                   Location Experience Level  Job Count
0         adelphi, maryland          Unknown          2
1               akron, ohio     senior level          1
2      alexandria, virginia          Unknown          1
3      alexandria, virginia     senior level          3
4       alpharetta, georgia        mid level          2
..                      ...              ...        ...
284          winters, texas     senior level          1
285   woburn, massachusetts          Unknown          3
286  woodbridge, new jersey     senior level          1
287      woodlawn, maryland        mid level          1
288      yakima, washington     senior level          1

[289 rows x 3 columns]

In [280]:
df['Sector']=df['Sector'].replace("-1",np.nan,regex=True)
experience_sector_stats = df.groupby(['Sector', 'Experience Level'])['Job Title'].count().reset_index()
experience_sector_stats = experience_sector_stats.rename(columns={'Job Title': 'Job Count'})

print(experience_sector_stats)

                        Sector Experience Level  Job Count
0           accounting & legal          Unknown          2
1           accounting & legal     senior level          1
2          aerospace & defense          Unknown          8
3          aerospace & defense      entry level          5
4          aerospace & defense        mid level         18
..                         ...              ...        ...
57  transportation & logistics      entry level          1
58  transportation & logistics        mid level          3
59  transportation & logistics     senior level          2
60            travel & tourism      entry level          2
61            travel & tourism        mid level          1

[62 rows x 3 columns]

In [281]:
#5

correlation = df['Founded'].corr(df['Average Salary'])

print(f"Correlation between Founding Year and Average Salary: {correlation}")

Correlation between Founding Year and Average Salary: 0.004358964295571058

In [ ]:

remote_rating_stats = df.groupby('Remote')['Rating'].mean()
print(remote_rating_stats)

In [311]:
df['Average Salary'] = pd.to_numeric(df['Average Salary'], errors='coerce').astype('Int64')
df['Average Salary'] = pd.to_numeric(df['Average Salary'], errors='coerce').astype(pd.Int32Dtype())


company_presence = df.groupby('Company Name')['Job Title'].count().reset_index()
company_presence = company_presence.rename(columns={'Job Title': 'Job Count'})
df = pd.merge(df, company_presence, on='Company Name', how='left')
competitor_salary_stats = df.groupby(['Job Count','Company Name'])['Average Salary'].mean()

print(competitor_salary_stats)

Job Count  Company Name
1          1010data                           107000.0
           10x genomics                       271500.0
           22nd century technologies          113000.0
           a place for mom                    103000.0
           a-line staffing solutions          136000.0
                                             ...
8          klaviyo                            133312.5
10         astrazeneca                        125350.0
11         tempus labs                   120090.909091
12         hatch data inc                     120500.0
           maxar technologies            150958.333333
Name: Average Salary, Length: 435, dtype: Float64

Data Transformation

In [315]:
#1

def has_skill(text, skill):
    return bool(re.search(skill, text, re.IGNORECASE))

df['Python'] = df['Job Description'].apply(lambda x: has_skill(x, r"python"))
df['SQL'] = df['Job Description'].apply(lambda x: has_skill(x, r"sql"))
df['Machine Learning'] = df['Job Description'].apply(lambda x: has_skill(x, r"machine learning|ml"))
df.head()

In [318]:
def has_benefit(text, benefit):
    return bool(re.search(benefit, text, re.IGNORECASE))

df['Healthcare'] = df['Job Description'].apply(lambda x: has_benefit(x, r"health\s?care|medical|insurance"))
df['Retirement Plan'] = df['Job Description'].apply(lambda x: has_benefit(x, r"retirement\s?plan|401k"))
df['Food']= df['Job Description'].apply(lambda x: has_benefit(x, r"free\s?food|meals"))
df.head()

In [321]:
df['Remote Job'] = df['Job Description'].apply(lambda x: has_skill(x, r"remote|telecommute|work from home"))
df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,Average Salary,At Headquarters,Job Count,Python,SQL,Machine Learning,Healthcare,Retirement Plan,Food,Remote Job
0,0,sr data scientist,137000-171000 (glassdoor est.),description the senior data scientist is resp...,3.1,healthfirst,"new york, new york","new york, new york",1001 to 5000 employees,1993,...,154000,True,2,False,False,True,True,False,False,False
1,1,data scientist,137000-171000 (glassdoor est.),"secure our nation, ignite your future join th...",4.2,mantech,"chantilly, virginia","herndon, virginia",5001 to 10000 employees,1968,...,154000,False,3,False,True,True,False,False,False,False
2,2,data scientist,137000-171000 (glassdoor est.),overview analysis group is one of the larges...,3.8,analysis group,"boston, massachusetts","boston, massachusetts",1001 to 5000 employees,1981,...,154000,True,3,True,False,True,True,False,False,False
3,3,data scientist,137000-171000 (glassdoor est.),job description: do you have a passion for da...,3.5,inficon,"newton, massachusetts","bad ragaz, switzerland",501 to 1000 employees,2000,...,154000,False,1,True,True,True,False,False,False,False
4,4,data scientist,137000-171000 (glassdoor est.),data scientist affinity solutions / marketing ...,2.9,affinity solutions,"new york, new york","new york, new york",51 to 200 employees,1998,...,154000,True,3,True,True,True,False,False,False,False

In [322]:
#2

import datetime

current_year = datetime.datetime.now().year
df['Company Age'] = df['Founded'].apply(lambda x: current_year - x if pd.notna(x) else np.nan)

In [335]:
def categorize_company_age(age):
    if pd.isna(age):
        return "unknown" 
    elif age < 10:
        return "New"
    elif 10 <= age <= 50:
        return "established"
    else:
        return "legacy"

df['Company Age Category'] = df['Company Age'].apply(categorize_company_age)

• Estimate Job Posting Age:  date information is not available, so we can't calculate how long ago each job posting was listed.

In [327]:
#3
sector_mapping = {
    'Information Technology': 'Technology',
    'Biotech & Pharmaceuticals': 'Healthcare',
    'Aerospace & Defense': 'Manufacturing',
    'Insurance': 'Finance',
    }

df['Sector'] = df['Industry'].map(sector_mapping).fillna(df['Sector'])  
df.head()

In [337]:


us_regions = {
    'Alabama': 'South', 'Alaska': 'West', 'Arizona': 'West', 'Arkansas': 'South', 'California': 'West',
    'Colorado': 'West', 'Connecticut': 'Northeast', 'Delaware': 'South', 'Florida': 'South',
    'Georgia': 'South', 'Hawaii': 'West', 'Idaho': 'West', 'Illinois': 'Midwest', 'Indiana': 'Midwest',
    'Iowa': 'Midwest', 'Kansas': 'Midwest', 'Kentucky': 'South', 'Louisiana': 'South',
    'Maine': 'Northeast', 'Maryland': 'South', 'Massachusetts': 'Northeast', 'Michigan': 'Midwest',
    'Minnesota': 'Midwest', 'Mississippi': 'South', 'Missouri': 'Midwest', 'Montana': 'West',
    'Nebraska': 'Midwest', 'Nevada': 'West', 'New Hampshire': 'Northeast', 'New Jersey': 'Northeast',
    'New Mexico': 'West', 'New York': 'Northeast', 'North Carolina': 'South', 'North Dakota': 'Midwest',
    'Ohio': 'Midwest', 'Oklahoma': 'South', 'Oregon': 'West', 'Pennsylvania': 'Northeast',
    'Rhode Island': 'Northeast', 'South Carolina': 'South', 'South Dakota': 'Midwest', 'Tennessee': 'South',
    'Texas': 'South', 'Utah': 'West', 'Vermont': 'Northeast', 'Virginia': 'South',
    'Washington': 'West', 'West Virginia': 'South', 'Wisconsin': 'Midwest', 'Wyoming': 'West',
    'District of Columbia': 'South'  
}


df['Region'] = df['Location'].str.split(', ').str[-1].map(us_regions).fillna('unknown')
df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,SQL,Machine Learning,Healthcare,Retirement Plan,Food,Remote Job,Company Age,Company Age Category,Region,Company Size Category
0,0,sr data scientist,137000-171000 (glassdoor est.),description the senior data scientist is resp...,3.1,healthfirst,"new york, new york","new york, new york",1001 to 5000 employees,1993,...,False,True,True,False,False,False,31.0,established,unknown,medium
1,1,data scientist,137000-171000 (glassdoor est.),"secure our nation, ignite your future join th...",4.2,mantech,"chantilly, virginia","herndon, virginia",5001 to 10000 employees,1968,...,True,True,False,False,False,False,56.0,legacy,unknown,large
2,2,data scientist,137000-171000 (glassdoor est.),overview analysis group is one of the larges...,3.8,analysis group,"boston, massachusetts","boston, massachusetts",1001 to 5000 employees,1981,...,False,True,True,False,False,False,43.0,established,unknown,medium
3,3,data scientist,137000-171000 (glassdoor est.),job description: do you have a passion for da...,3.5,inficon,"newton, massachusetts","bad ragaz, switzerland",501 to 1000 employees,2000,...,True,True,False,False,False,False,24.0,established,unknown,medium
4,4,data scientist,137000-171000 (glassdoor est.),data scientist affinity solutions / marketing ...,2.9,affinity solutions,"new york, new york","new york, new york",51 to 200 employees,1998,...,True,True,False,False,False,False,26.0,established,unknown,small

In [333]:
def categorize_size(size_str):
    try:
        size_num = int(''.join(filter(str.isdigit, size_str.split()[0])))
        if size_num < 500:
            return "small"
        elif 500 <= size_num <= 5000:
            return "medium"
        else:
            return "large"
    except ValueError:
        return "unknown" 

df['Company Size Category'] = df['Size'].apply(categorize_size)

In [336]:
df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,SQL,Machine Learning,Healthcare,Retirement Plan,Food,Remote Job,Company Age,Company Age Category,Region,Company Size Category
0,0,sr data scientist,137000-171000 (glassdoor est.),description the senior data scientist is resp...,3.1,healthfirst,"new york, new york","new york, new york",1001 to 5000 employees,1993,...,False,True,True,False,False,False,31.0,established,Unknown,medium
1,1,data scientist,137000-171000 (glassdoor est.),"secure our nation, ignite your future join th...",4.2,mantech,"chantilly, virginia","herndon, virginia",5001 to 10000 employees,1968,...,True,True,False,False,False,False,56.0,legacy,Unknown,large
2,2,data scientist,137000-171000 (glassdoor est.),overview analysis group is one of the larges...,3.8,analysis group,"boston, massachusetts","boston, massachusetts",1001 to 5000 employees,1981,...,False,True,True,False,False,False,43.0,established,Unknown,medium
3,3,data scientist,137000-171000 (glassdoor est.),job description: do you have a passion for da...,3.5,inficon,"newton, massachusetts","bad ragaz, switzerland",501 to 1000 employees,2000,...,True,True,False,False,False,False,24.0,established,Unknown,medium
4,4,data scientist,137000-171000 (glassdoor est.),data scientist affinity solutions / marketing ...,2.9,affinity solutions,"new york, new york","new york, new york",51 to 200 employees,1998,...,True,True,False,False,False,False,26.0,established,Unknown,small

In [343]:
#4
df['EmployeeSize'] = df['Size'].str.extract(r'(\d+)(?!.*\d)')
df['EmployeeSize'] = pd.to_numeric(df['EmployeeSize'], errors='coerce').astype(float)
df['RevenuePerEmployee'] = (df['MinRevenue'] + df['MaxRevenue']) / (2 * df['EmployeeSize'])
df.head()

In [345]:
#2080 working  hours in a year
#260 working days in a year

def normalize_salary(row):
    salary_estimate = row['Salary Estimate']
    salary_type = row['Salary Type']
    
    try:
        salary_numbers = re.findall(r'\d+', salary_estimate)
        min_salary = int(salary_numbers[0])
        max_salary = int(salary_numbers[1]) if len(salary_numbers) > 1 else min_salary
        
        if salary_type == 'per hour':
            return (min_salary + max_salary) / 2 * 2080 
        elif salary_type == 'per day':
            return (min_salary + max_salary) / 2 * 260
        else:  # Assume 'per year'
            return (min_salary + max_salary) / 2  
            
    except (IndexError, ValueError):
        return np.nan 

df['NormalizedSalary'] = df.apply(normalize_salary, axis=1)

In [349]:
df.head(632)

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,Food,Remote Job,Company Age,Company Age Category,Region,Company Size Category,EmployeeSize,RevenuePerEmployee,NormalizedSalary,SalaryBucket
0,0,sr data scientist,137000-171000 (glassdoor est.),description the senior data scientist is resp...,3.1,healthfirst,"new york, new york","new york, new york",1001 to 5000 employees,1993,...,False,False,31.0,established,unknown,medium,5000.0,<NA>,154000.0,>$100k
1,1,data scientist,137000-171000 (glassdoor est.),"secure our nation, ignite your future join th...",4.2,mantech,"chantilly, virginia","herndon, virginia",5001 to 10000 employees,1968,...,False,False,56.0,legacy,unknown,large,10000.0,100000.0,154000.0,>$100k
2,2,data scientist,137000-171000 (glassdoor est.),overview analysis group is one of the larges...,3.8,analysis group,"boston, massachusetts","boston, massachusetts",1001 to 5000 employees,1981,...,False,False,43.0,established,unknown,medium,5000.0,20000.0,154000.0,>$100k
3,3,data scientist,137000-171000 (glassdoor est.),job description: do you have a passion for da...,3.5,inficon,"newton, massachusetts","bad ragaz, switzerland",501 to 1000 employees,2000,...,False,False,24.0,established,unknown,medium,1000.0,100000.0,154000.0,>$100k
4,4,data scientist,137000-171000 (glassdoor est.),data scientist affinity solutions / marketing ...,2.9,affinity solutions,"new york, new york","new york, new york",51 to 200 employees,1998,...,False,False,26.0,established,unknown,small,200.0,<NA>,154000.0,>$100k
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
627,627,data scientist,87000-141000 (glassdoor est.),job description data scientist location: the ...,4.6,murray resources,"the woodlands, texas","houston, texas",1 to 50 employees,1988,...,False,False,36.0,established,unknown,small,50.0,200000.0,114000.0,>$100k
628,628,data scientist,87000-141000 (glassdoor est.),"geotab, a global leader in iot and connected t...",4.3,geotab,"oakville, california","oakville, canada",1001 to 5000 employees,2000,...,False,False,24.0,established,unknown,medium,5000.0,20000.0,114000.0,>$100k
629,629,data scientist,87000-141000 (glassdoor est.),job description data scientist duration: 6+ mo...,4.7,crs group,"chicago, illinois","itasca, illinois",51 to 200 employees,1994,...,False,False,30.0,established,unknown,small,200.0,50000.0,114000.0,>$100k
630,630,data scientist,87000-141000 (glassdoor est.),"eglobaltech, one of northern virginia’s fastes...",3.7,eglobaltech,"arlington, virginia","vienna, virginia",201 to 500 employees,2004,...,False,False,20.0,established,unknown,small,500.0,<NA>,114000.0,>$100k
631,631,"data scientist, kinship - nyc/portland",92000-155000 (glassdoor est.),back to search results previous job next job ...,3.9,mars,"new york, new york","mc lean, virginia",10000+ employees,1911,...,False,False,113.0,legacy,unknown,large,10000.0,-83134.8736,123500.0,>$100k

In [348]:
def categorize_salary(salary):
    if pd.isna(salary):
        return "Unknown"
    elif salary < 50000:
        return "<$50k"
    elif 50000 <= salary <= 100000:
        return "$50k-$100k"
    else:
        return ">$100k"

df['SalaryBucket'] = df['NormalizedSalary'].apply(categorize_salary)
df['SalaryBucket']

In [350]:
#5
df['Competitor Count'] = df['Competitors'].str.split(', ').str.len().fillna(0).astype(int)

In [415]:

all_competitors = df['Competitors'].str.split(', ').explode().dropna().value_counts()

common_competitor_threshold = 5 
common_competitors = all_competitors[all_competitors >= common_competitor_threshold].index.tolist()
df['Has Common Competitors'] = df['Competitors'].str.contains('|'.join(common_competitors), na=False).astype(bool)
df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,Company Age Category,Region,Company Size Category,EmployeeSize,RevenuePerEmployee,NormalizedSalary,SalaryBucket,Competitor Count,Has Common Competitors,Has Competitors
0,0,sr data scientist,137000-171000 (glassdoor est.),description the senior data scientist is resp...,3.1,healthfirst,"new york, new york","new york, new york",1001 to 5000 employees,1993,...,established,new york,medium,5000,<NA>,154000.0,>$100k,3,False,True
1,1,data scientist,137000-171000 (glassdoor est.),"secure our nation, ignite your future join th...",4.2,mantech,"chantilly, virginia","herndon, virginia",5001 to 10000 employees,1968,...,legacy,virginia,large,10000,100000.0,154000.0,>$100k,1,True,True
2,2,data scientist,137000-171000 (glassdoor est.),overview analysis group is one of the larges...,3.8,analysis group,"boston, massachusetts","boston, massachusetts",1001 to 5000 employees,1981,...,established,massachusetts,medium,5000,20000.0,154000.0,>$100k,1,True,True
3,3,data scientist,137000-171000 (glassdoor est.),job description: do you have a passion for da...,3.5,inficon,"newton, massachusetts","bad ragaz, switzerland",501 to 1000 employees,2000,...,established,massachusetts,medium,1000,100000.0,154000.0,>$100k,3,False,True
4,4,data scientist,137000-171000 (glassdoor est.),data scientist affinity solutions / marketing ...,2.9,affinity solutions,"new york, new york","new york, new york",51 to 200 employees,1998,...,established,new york,small,200,<NA>,154000.0,>$100k,3,False,True

In [353]:

avg_rating_common_competitors = df[df['Has Common Competitors']]['Rating'].mean()
avg_rating_others = df[~df['Has Common Competitors']]['Rating'].mean()

print(f"Average rating for companies with common competitors: {avg_rating_common_competitors}")
print(f"Average rating for other companies: {avg_rating_others}")


avg_salary_common_competitors = df[df['Has Common Competitors']]['NormalizedSalary'].mean()
avg_salary_others = df[~df['Has Common Competitors']]['NormalizedSalary'].mean()

print(f"Average salary for companies with common competitors: {avg_salary_common_competitors}")
print(f"Average salary for other companies: {avg_salary_others}")

Average rating for companies with common competitors: 3.4746429920196533
Average rating for other companies: 3.7383925914764404
Average salary for companies with common competitors: 124115.17857142857
Average salary for other companies: 121406.25

Comparative Analysis

In [354]:
#1
rating_comparison = df.groupby(['Sector', 'Industry'])['Rating'].mean().reset_index()
rating_comparison = rating_comparison.sort_values(['Sector', 'Rating'], ascending=[True, False])

print(rating_comparison)

                                Sector  \
0                   accounting & legal
1                  aerospace & defense
2               agriculture & forestry
3               agriculture & forestry
4            biotech & pharmaceuticals
9                    business services
8                    business services
5                    business services
7                    business services
6                    business services
10                   business services
11  construction, repair & maintenance
12                   consumer services
13                           education
17                             finance
18                             finance
16                             finance
14                             finance
15                             finance
19                          government
20                          government
21                         health care
22              information technology
23              information technology
24              information technology
25              information technology
27                           insurance
26                           insurance
34                       manufacturing
31                       manufacturing
32                       manufacturing
33                       manufacturing
29                       manufacturing
30                       manufacturing
28                       manufacturing
36                               media
37                               media
35                               media
38                          non-profit
39        oil, gas, energy & utilities
41        oil, gas, energy & utilities
40        oil, gas, energy & utilities
42                         real estate
45                              retail
46                              retail
43                              retail
44                              retail
48                  telecommunications
49                  telecommunications
47                  telecommunications
54          transportation & logistics
53          transportation & logistics
50          transportation & logistics
51          transportation & logistics
52          transportation & logistics
55                    travel & tourism
56                    travel & tourism

                                    Industry    Rating
0                                 accounting  4.166667
1                        aerospace & defense  3.782609
2                      farm support services       3.5
3                          timber operations       3.3
4                  biotech & pharmaceuticals  3.683333
9                     staffing & outsourcing  4.147223
8                     research & development  3.870588
5                    advertising & marketing       3.8
7                                 consulting  3.660527
6       architectural & engineering services       3.6
10                                 wholesale  2.633333
11                              construction       3.4
12                 health, beauty, & fitness       4.0
13                   colleges & universities       3.0
17                                   lending    4.4125
18          venture capital & private equity       4.4
16     investment banking & asset management  3.815384
14                     banks & credit unions    3.6875
15          financial transaction processing       3.6
19                          federal agencies     3.975
20                 state & regional agencies       3.2
21          health care services & hospitals  3.304762
22              computer hardware & software  4.238596
23   enterprise software & network solutions  4.093023
24                                  internet  3.825926
25                               it services  3.780328
27                        insurance carriers  3.635714
26           insurance agencies & brokerages       3.3
34    transportation equipment manufacturing       4.6
31             food & beverage manufacturing       3.9
32                  industrial manufacturing       3.7
33               miscellaneous manufacturing       3.7
29           consumer products manufacturing       3.6
30     electrical & electronic manufacturing  3.466666
28                    chemical manufacturing  3.366667
36                                publishing       4.7
37                               video games  4.466667
35                               news outlet       3.3
38                         social assistance       2.8
39                                    energy       3.7
41                                 utilities  3.466666
40                        oil & gas services       2.9
42                               real estate       3.9
45                    food & beverage stores       3.7
46                       other retail stores  3.666667
43  consumer electronics & appliances stores       3.5
44       department, clothing, & shoe stores       3.5
48          telecommunications manufacturing       3.3
49               telecommunications services      3.24
47     cable, internet & telephone providers       2.9
54                 transportation management       3.7
53                                  shipping       3.4
50                 express delivery services       3.2
51                  logistics & supply chain       3.1
52                                      rail       2.8
55                 hotels, motels, & resorts       3.5
56                           travel agencies       3.5

In [355]:
top_sectors = df['Sector'].value_counts().head(3).index.tolist()
top_sectors_df = df[df['Sector'].isin(top_sectors)]
salary_range_comparison = top_sectors_df.groupby(['Sector', 'Industry'])['Average Salary'].median().reset_index()
salary_range_comparison = salary_range_comparison.sort_values(['Sector', 'Average Salary'], ascending=[True, False])

print(salary_range_comparison)

                       Sector                                 Industry  \
0   biotech & pharmaceuticals                biotech & pharmaceuticals
2           business services     architectural & engineering services
6           business services                                wholesale
3           business services                               consulting
4           business services                   research & development
5           business services                   staffing & outsourcing
1           business services                  advertising & marketing
8      information technology  enterprise software & network solutions
7      information technology             computer hardware & software
9      information technology                                 internet
10     information technology                              it services

    Average Salary
0         106000.0
2         161000.0
6         136000.0
3         115500.0
4         114000.0
5         113000.0
1         107000.0
8         115500.0
7         114000.0
9         106000.0
10        106000.0

In [356]:

revenue_by_sector = df.groupby('Sector').agg({'MinRevenue': 'mean', 'MaxRevenue': 'mean'}).reset_index()
revenue_by_sector = revenue_by_sector.sort_values('MaxRevenue', ascending=False)

print(revenue_by_sector)

                                Sector         MinRevenue         MaxRevenue
19                  telecommunications       1390189152.0  1191590701.714286
16        oil, gas, energy & utilities  1350197284.571429        945138099.2
20          transportation & logistics  1772044970.666667   886022485.333333
1                  aerospace & defense  1054701337.263158    871275017.73913
12                           insurance       1036205504.0        841916972.0
13                       manufacturing   814674283.636364   779253662.608696
17                         real estate       1050000000.0        700000000.0
2               agriculture & forestry       1000000000.0   666666666.666667
3            biotech & pharmaceuticals   791855930.434783   551899587.878788
18                              retail        703226982.4   502304987.428571
9                           government        626344576.0   442125583.058824
8                              finance   596006424.380952   379276815.515152
10                         health care   577570284.307692   357543509.333333
4                    business services   362486833.391304   277906572.266667
11              information technology   391027785.714286   232952723.404255
14                               media        350000000.0        210000000.0
5   construction, repair & maintenance        100000000.0        100000000.0
15                          non-profit         25000000.0         25000000.0
6                    consumer services          5000000.0          5000000.0
0                   accounting & legal                0.0                0.0
7                            education               <NA>                0.0
21                    travel & tourism               <NA>                0.0

In [377]:
#2
public_companies = df[df['Type of ownership'].str.contains('public', na=False)]

private_companies = df[df['Type of ownership'].str.contains('private', na=False)]
avg_salary_public = public_companies['Average Salary'].mean()
avg_salary_private = private_companies['Average Salary'].mean()

print(f"Average Salary for Public Companies: {avg_salary_public}")
print(f"Average Salary for Private Companies: {avg_salary_private}")

Average Salary for Public Companies: 123127.45098039215
Average Salary for Private Companies: 115288.02992518703

In [380]:
df['Type of ownership']=df['Type of ownership'].replace("-1",np.nan,regex=True)
ownership_groups = df.groupby('Type of ownership')
mean_ratings = ownership_groups['Rating'].mean()
median_ratings = ownership_groups['Rating'].median()
std_ratings = ownership_groups['Rating'].std()

print("Mean Ratings by Ownership:")
print(mean_ratings)
print("\nMedian Ratings by Ownership:")
print(median_ratings)
print("\nStandard Deviation of Ratings by Ownership:")
print(std_ratings)

Mean Ratings by Ownership:
Type of ownership
college / university                   3.0
company - private                 3.763728
company - public                  3.692157
contract                              3.95
government                            3.76
hospital                               4.1
nonprofit organization            3.608333
other organization                     3.5
private practice / firm                2.6
self-employed                          3.3
subsidiary or business segment    3.835714
unknown                                0.5
Name: Rating, dtype: Float32

Median Ratings by Ownership:
Type of ownership
college / university               2.6
company - private                  3.9
company - public                   3.7
contract                          3.95
government                         3.7
hospital                           4.1
nonprofit organization            3.65
other organization                 3.9
private practice / firm            3.8
self-employed                      3.3
subsidiary or business segment     3.8
unknown                           -1.0
Name: Rating, dtype: Float32

Standard Deviation of Ratings by Ownership:
Type of ownership
college / university               0.69282
company - private                 1.200103
company - public                  0.696091
contract                          1.484924
government                        0.371782
hospital                              <NA>
nonprofit organization            0.456931
other organization                 0.69282
private practice / firm                2.4
self-employed                          0.0
subsidiary or business segment    0.539694
unknown                                3.0
Name: Rating, dtype: Float32

In [395]:
df['EmployeeSize']= pd.to_numeric(df['EmployeeSize'], errors='coerce').astype('Int64')
df['EmployeeSize']=pd.to_numeric(df['EmployeeSize'], errors='coerce').astype(pd.Int32Dtype())

ownership_groups = df.groupby('Type of ownership')
mean_sizes = ownership_groups['EmployeeSize'].mean() 
median_sizes = ownership_groups['EmployeeSize'].median()
size_quartiles = ownership_groups['EmployeeSize'].quantile([0.25, 0.75])

print("Mean Company Size by Ownership:")
print(mean_sizes)
print("\nMedian Company Size by Ownership:")
print(median_sizes)
print("\nCompany Size Quartiles by Ownership:")
print(size_quartiles)

Mean Company Size by Ownership:
Type of ownership
college / university                   1000.0
company - private                 1497.820513
company - public                  7254.391892
contract                                525.0
government                        5666.666667
hospital                              10000.0
nonprofit organization            5372.222222
other organization                     8000.0
private practice / firm                3762.5
self-employed                         10000.0
subsidiary or business segment    3438.461538
unknown                                  50.0
Name: EmployeeSize, dtype: Float64

Median Company Size by Ownership:
Type of ownership
college / university               1000.0
company - private                   200.0
company - public                  10000.0
contract                            525.0
government                         5000.0
hospital                          10000.0
nonprofit organization             5000.0
other organization                10000.0
private practice / firm            5000.0
self-employed                     10000.0
subsidiary or business segment     1000.0
unknown                              50.0
Name: EmployeeSize, dtype: Float64

Company Size Quartiles by Ownership:
Type of ownership
college / university            0.25     1000.0
                                0.75     1000.0
company - private               0.25      200.0
                                0.75     1000.0
company - public                0.25     5000.0
                                0.75    10000.0
contract                        0.25      287.5
                                0.75      762.5
government                      0.25     5000.0
                                0.75     5000.0
hospital                        0.25    10000.0
                                0.75    10000.0
nonprofit organization          0.25     1000.0
                                0.75    10000.0
other organization              0.25     5000.0
                                0.75    10000.0
private practice / firm         0.25     3762.5
                                0.75     5000.0
self-employed                   0.25    10000.0
                                0.75    10000.0
subsidiary or business segment  0.25      500.0
                                0.75     5000.0
unknown                         0.25       50.0
                                0.75       50.0
Name: EmployeeSize, dtype: Float64

In [397]:
#3
# 1. Create age groups (example)
age_group = pd.cut(df['Founded'], bins=[0, 2000, 2010, float('inf')], labels=['Before 2000', '2000-2010', 'After 2010'])

age_groups = df.groupby(age_group)

avg_ratings_by_age = age_groups['Rating'].mean()

print("Average Ratings by Age Group:")
print(avg_ratings_by_age)
age_groups = df.groupby('Company Age')

Average Ratings by Age Group:
Founded
Before 2000    3.734884
2000-2010      3.957018
After 2010     4.083088
Name: Rating, dtype: Float32

C:\Users\sebsn\AppData\Local\Temp\ipykernel_28620\388528756.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  age_groups = df.groupby(age_group)

In [398]:
older_companies = df[df['Founded'] < 2000]
newer_companies = df[df['Founded'] >= 2000]

std_ratings_older = older_companies['Rating'].std()
std_ratings_newer = newer_companies['Rating'].std()

print("Standard Deviation of Ratings (Older Companies):", std_ratings_older)
print("Standard Deviation of Ratings (Newer Companies):", std_ratings_newer)

Standard Deviation of Ratings (Older Companies): 0.5023503
Standard Deviation of Ratings (Newer Companies): 0.7342657

In [399]:
sector_counts_by_age = df.groupby([age_group, 'Sector']).size()
sector_proportions_by_age = sector_counts_by_age.groupby(level=0).apply(lambda x: x / float(x.sum()))

print("Sector Proportions by Age Group:")
print(sector_proportions_by_age)

Sector Proportions by Age Group:
Founded      Founded      Sector
Before 2000  Before 2000  accounting & legal            0.000000
                          aerospace & defense           0.067114
                          agriculture & forestry        0.006711
                          biotech & pharmaceuticals     0.100671
                          business services             0.231544
                                                          ...
After 2010   After 2010   real estate                   0.014706
                          retail                        0.007353
                          telecommunications            0.014706
                          transportation & logistics    0.022059
                          travel & tourism              0.014706
Length: 66, dtype: float64

C:\Users\sebsn\AppData\Local\Temp\ipykernel_28620\2449185851.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sector_counts_by_age = df.groupby([age_group, 'Sector']).size()
C:\Users\sebsn\AppData\Local\Temp\ipykernel_28620\2449185851.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  sector_proportions_by_age = sector_counts_by_age.groupby(level=0).apply(lambda x: x / float(x.sum()))

In [403]:
#4
regions = df['Location'].str.split(', ', expand=True)[1] 
df['Region'] = regions

region_groups = df.groupby('Region')

avg_salary_by_region = region_groups['Average Salary'].mean()

print("Average Salary by Region:")
print(avg_salary_by_region)

Average Salary by Region:
Region
alabama                      131125.0
anne arundel                  89000.0
arizona                      140875.0
california              118366.666667
colorado                     103650.0
connecticut                   98125.0
delaware                     271500.0
district of columbia         139500.0
florida                      118437.5
georgia                  89111.111111
illinois                114716.666667
indiana                      113400.0
iowa                     79166.666667
kansas                       103000.0
louisiana                    103000.0
maryland                108230.769231
massachusetts           121967.741935
michigan                      82000.0
minnesota                     94000.0
mississippi                  133000.0
missouri                114958.333333
nebraska                107666.666667
new hampshire                132000.0
new jersey                   120600.0
new york                122201.923077
north carolina          150111.111111
ohio                         108500.0
oklahoma                122916.666667
oregon                       132000.0
pennsylvania            110416.666667
rhode island                  38250.0
south carolina                96000.0
tennessee                    102187.5
texas                   125176.470588
utah                    104833.333333
virginia                120533.707865
washington                  134781.25
west virginia                114000.0
wisconsin               144416.666667
Name: Average Salary, dtype: Float64

In [401]:
remote_roles = df[df['Remote'] == 'yes']
onsite_roles = df[df['Remote'] == 'no']

avg_salary_remote = remote_roles['AverageSalary'].mean()
avg_salary_onsite = onsite_roles['AverageSalary'].mean()

job_count_remote = len(remote_roles)
job_count_onsite = len(onsite_roles)

avg_rating_remote = remote_roles['Rating'].mean()
avg_rating_onsite = onsite_roles['Rating'].mean()

print("Remote Roles:")
print("Average Salary:", avg_salary_remote)
print("Job Count:", job_count_remote)
print("Average Rating:", avg_rating_remote)

print("\nOnsite Roles:")
print("Average Salary:", avg_salary_onsite)
print("Job Count:", job_count_onsite)
print("Average Rating:", avg_rating_onsite)

0             new york, new york
1            chantilly, virginia
2          boston, massachusetts
3          newton, massachusetts
4             new york, new york
                 ...
667         fort lee, new jersey
668    san francisco, california
669        irwindale, california
670    san francisco, california
671           new york, new york
Name: Location, Length: 672, dtype: object

In [407]:
state_groups = df.groupby('Location') 
job_count_by_state = state_groups.size()
avg_salary_by_state = state_groups['Average Salary'].mean()

state_stats = pd.DataFrame({'Job Count': job_count_by_state, 'Average Salary': avg_salary_by_state})
state_stats = state_stats.sort_values('Job Count', ascending=False)

print("Job Count and Average Salary by State:")
print(state_stats)

Job Count and Average Salary by State:
                                  Job Count  Average Salary
Location
san francisco, california                69   116543.478261
new york, new york                       50        121880.0
washington, district of columbia         26        139500.0
boston, massachusetts                    24   122583.333333
chicago, illinois                        22   112909.090909
...                                     ...             ...
fremont, california                       1        136500.0
oakville, california                      1        114000.0
gahanna, ohio                             1        106000.0
germantown, maryland                      1        106000.0
yakima, washington                        1        105000.0

[207 rows x 2 columns]

In [413]:
#5
Has_Competitors = df['Competitors'].notna()

# 2. Group by competitor status
competitor_groups = df.groupby(Has_Competitors)

# 3. Calculate average salary
avg_salary_by_competitor_status = competitor_groups['Average Salary'].mean()

# 4. Compare average salaries
print("Average Salary by Competitor Status:")
print(avg_salary_by_competitor_status)

Average Salary by Competitor Status:
Has Common Competitors
True    118157.738095
Name: Average Salary, dtype: Float64

In [416]:
industry_groups = df.groupby('Industry')

avg_founding_year_by_industry = industry_groups['Founded'].mean()

sorted_industries = avg_founding_year_by_industry.sort_values()

print("Average Founding Year by Industry (Sorted):")
print(sorted_industries)

Average Founding Year by Industry (Sorted):
Industry
timber operations                                1880.0
insurance agencies & brokerages                  1909.5
food & beverage manufacturing                    1911.0
insurance carriers                          1930.285714
architectural & engineering services             1935.0
industrial manufacturing                    1939.333333
consumer products manufacturing                  1941.6
energy                                           1942.2
chemical manufacturing                      1954.333333
banks & credit unions                          1954.625
logistics & supply chain                         1956.0
-1                                          1959.333333
transportation equipment manufacturing           1967.5
wholesale                                   1968.666667
department, clothing, & shoe stores              1969.0
research & development                      1970.058824
telecommunications manufacturing                 1971.0
biotech & pharmaceuticals                   1975.377049
aerospace & defense                         1976.441176
federal agencies                               1981.375
rail                                             1983.0
colleges & universities                          1984.0
health care services & hospitals            1986.777778
social assistance                                1987.0
investment banking & asset management       1987.615385
consumer electronics & appliances stores         1990.0
hotels, motels, & resorts                        1990.0
consulting                                  1990.433333
staffing & outsourcing                      1993.058824
oil & gas services                               1996.0
financial transaction processing                 1996.0
lending                                        1997.125
advertising & marketing                     1997.714286
venture capital & private equity                 1998.0
construction                                     1998.0
computer hardware & software                1998.035714
utilities                                   1998.333333
miscellaneous manufacturing                      1999.0
telecommunications services                      2000.8
other retail stores                              2004.5
it services                                 2004.576923
video games                                      2006.0
shipping                                         2006.0
internet                                    2006.185185
electrical & electronic manufacturing       2006.666667
news outlet                                      2007.0
enterprise software & network solutions     2008.238095
express delivery services                        2011.0
transportation management                        2011.0
travel agencies                                  2011.0
real estate                                 2011.333333
farm support services                            2014.0
cable, internet & telephone providers            2016.0
accounting                                         <NA>
food & beverage stores                             <NA>
health, beauty, & fitness                          <NA>
publishing                                         <NA>
state & regional agencies                          <NA>
Name: Founded, dtype: Float64

In [417]:

industry_avg_salaries = df.groupby('Industry')['Average Salary'].mean()

Slry_deviation = df.apply(lambda row: row['Average Salary'] - industry_avg_salaries[row['Industry']], axis=1)
correlation1 = df['Rating'].corr(Slry_deviation)

print("Correlation between Rating and Salary Deviation:", correlation1)

Correlation between Rating and Salary Deviation: -0.04578559756450044

Advanced Data Insights and Parsing